#ifndef NETCHESSZX_SPECTRUM_LOWRAM_MAP_H
#define NETCHESSZX_SPECTRUM_LOWRAM_MAP_H

#ifdef NETCHESSZX_SPRINTER

/* Sprinter keeps shared overlay state in permanent WIN2.  This generated
   header comes from src/sprinter/fixed_layout.json; none of the Spectrum
   0x5B00-0x67FF addresses are valid on this target. */
#include "sprinter_layout.h"

#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR SPRINTER_OVERLAY_CONTEXT
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE 8u

#else

/* 0x5b00-0x5bff: ZX printer buffer, untouched by the ROM IM1 ISR and esxDOS.
   Reclaimed for the UART RX ring (exactly 256 bytes, ends right where the
   0x5c00 sysvars the ROM ISR does touch begin). */
#define NETCHESSZX_LOWRAM_UART_RING_ADDR 0x5b00
#define NETCHESSZX_LOWRAM_UART_RING_SIZE 0x100
#define NETCHESSZX_LOWRAM_MOVE_LOG_ADDR 0x5cb6
#define NETCHESSZX_LOWRAM_MOVE_LOG_SIZE 0xe0
#define NETCHESSZX_LOWRAM_CHAT_LOG_ADDR 0x5d96
#define NETCHESSZX_LOWRAM_CHAT_LOG_SIZE 0xfc
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR 0x5e92
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_SIZE 0x08
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR 0x5e9a
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_SIZE 0x18
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR 0x5eb2
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_SIZE 0x2b
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR 0x5edd
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_SIZE 0x40
#define NETCHESSZX_LOWRAM_STATUS_ADDR 0x5f3a
#define NETCHESSZX_LOWRAM_STATUS_SIZE 0x26
#define NETCHESSZX_LOWRAM_STATUS_TEXT_END 0x5f5f
#define NETCHESSZX_LOWRAM_LAST_IP_ADDR NETCHESSZX_LOWRAM_STATUS_ADDR
#define NETCHESSZX_LOWRAM_LAST_IP_SIZE 18u
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR \
    (NETCHESSZX_LOWRAM_LAST_IP_ADDR + NETCHESSZX_LOWRAM_LAST_IP_SIZE)
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_SIZE 16u
#define NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR 0x5f60
#define NETCHESSZX_LOWRAM_BOARD_CELL_COUNT 64u
#define NETCHESSZX_LOWRAM_RULES_BOARD_ADDR 0x5fa0
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR 0x5fe0
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE 8u
#define NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR 0x5ff0
#define NETCHESSZX_LOWRAM_HINTED_ROWS_SIZE 8u

/* Shared only by the currently loaded overlay. ABOUT input and Next sprite
   staging reuse adjacent/overlapping bytes outside overlay-call lifetime;
   no overlay may retain this pointer after returning to resident code. */
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_ADDR 0x672bu
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_SIZE 160u
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_END \
    (NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_ADDR + \
     NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_SIZE)

#define NETCHESSZX_LOWRAM_MOVE_LOG_END \
    (NETCHESSZX_LOWRAM_MOVE_LOG_ADDR + NETCHESSZX_LOWRAM_MOVE_LOG_SIZE)
#define NETCHESSZX_LOWRAM_CHAT_LOG_END \
    (NETCHESSZX_LOWRAM_CHAT_LOG_ADDR + NETCHESSZX_LOWRAM_CHAT_LOG_SIZE)
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_END \
    (NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR + NETCHESSZX_LOWRAM_CLOCK_SAVE_SIZE)
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_END \
    (NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR + \
     NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_SIZE)
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_END \
    (NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR + NETCHESSZX_LOWRAM_LOCAL_INPUT_SIZE)
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_END \
    (NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR + NETCHESSZX_LOWRAM_INPUT_HISTORY_SIZE)
#define NETCHESSZX_LOWRAM_STATUS_END \
    (NETCHESSZX_LOWRAM_STATUS_ADDR + NETCHESSZX_LOWRAM_STATUS_SIZE)
#define NETCHESSZX_LOWRAM_LAST_IP_END \
    (NETCHESSZX_LOWRAM_LAST_IP_ADDR + NETCHESSZX_LOWRAM_LAST_IP_SIZE)
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_END \
    (NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR + \
     NETCHESSZX_LOWRAM_MQTT_PRESENCE_SIZE)
#define NETCHESSZX_LOWRAM_CHESS_BOARD_END \
    (NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR + NETCHESSZX_LOWRAM_BOARD_CELL_COUNT)
#define NETCHESSZX_LOWRAM_RULES_BOARD_END \
    (NETCHESSZX_LOWRAM_RULES_BOARD_ADDR + NETCHESSZX_LOWRAM_BOARD_CELL_COUNT)
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_END \
    (NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR + NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE)
#define NETCHESSZX_LOWRAM_HINTED_ROWS_END \
    (NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR + NETCHESSZX_LOWRAM_HINTED_ROWS_SIZE)

#if (NETCHESSZX_LOWRAM_UART_RING_ADDR + NETCHESSZX_LOWRAM_UART_RING_SIZE) > 0x5c00
#error "low-RAM UART ring overlaps ROM sysvars"
#endif
#if NETCHESSZX_LOWRAM_MOVE_LOG_END > NETCHESSZX_LOWRAM_CHAT_LOG_ADDR
#error "low-RAM move log overlaps chat log"
#endif
#if NETCHESSZX_LOWRAM_CHAT_LOG_END != NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR
#error "low-RAM chat log must end at clock save"
#endif
#if NETCHESSZX_LOWRAM_CLOCK_SAVE_END != NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR
#error "low-RAM clock save must end at game timer save"
#endif
#if NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_END != NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR
#error "low-RAM game timer save must end at local input"
#endif
#if NETCHESSZX_LOWRAM_LOCAL_INPUT_END > NETCHESSZX_LOWRAM_STATUS_ADDR
#error "low-RAM local input overlaps status buffer"
#endif
#if NETCHESSZX_LOWRAM_LOCAL_INPUT_END != NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR
#error "low-RAM input history must follow local input"
#endif
#if NETCHESSZX_LOWRAM_INPUT_HISTORY_END > NETCHESSZX_LOWRAM_STATUS_ADDR
#error "low-RAM input history overlaps status buffer"
#endif
#if NETCHESSZX_LOWRAM_STATUS_TEXT_END + 1 != NETCHESSZX_LOWRAM_STATUS_END
#error "low-RAM status text end must be final status byte"
#endif
#if NETCHESSZX_LOWRAM_LAST_IP_END != NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR
#error "low-RAM last-ip must end at MQTT presence scratch"
#endif
#if NETCHESSZX_LOWRAM_MQTT_PRESENCE_END > NETCHESSZX_LOWRAM_STATUS_END
#error "low-RAM network status scratch exceeds status buffer"
#endif
#if NETCHESSZX_LOWRAM_STATUS_END != NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR
#error "low-RAM status buffer must end at chess board"
#endif
#if NETCHESSZX_LOWRAM_CHESS_BOARD_END != NETCHESSZX_LOWRAM_RULES_BOARD_ADDR
#error "low-RAM chess board must end at rules board"
#endif
#if NETCHESSZX_LOWRAM_RULES_BOARD_END != NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR
#error "low-RAM rules board must end at overlay context"
#endif
#if NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_END > NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR
#error "low-RAM overlay context overlaps hinted rows"
#endif
#if NETCHESSZX_LOWRAM_HINTED_ROWS_END > 0x6000
#error "low-RAM hinted rows exceed reserved page"
#endif
#if NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_END > 0x6800u
#error "overlay-only scratch overlaps overlay code slot"
#endif

#endif /* NETCHESSZX_SPRINTER */

#endif
