#ifndef NETCHESSZX_SPECTRUM_LOWRAM_MAP_H
#define NETCHESSZX_SPECTRUM_LOWRAM_MAP_H

#if defined(NETCHESSZX_SPRINTER)

/* Sprinter (plan D3): same fixed-shared-address model as ZX/Next -- resident
   C and each separately linked overlay .c must agree on these addresses out
   of band, same reason RTC_PRESENT is fixed rather than EXTERNed (port.md
   S5). The flat #4000-#BFFF resident has no 48K sysvars to dodge and no byte
   budget tight enough to justify ZX's overlapping aliases (LAST_IP/
   MQTT_PRESENCE packed inside STATUS), so buffers here sit back-to-back with
   no aliasing. src/sprinter/fixed_layout.json's LOWRAM_* regions are the
   actual source of truth; its own validator (gen_sprinter_layout.py, run by
   the sprinter-layout-check build step) proves no overlap, so the ZX
   branch's #error chain below is not duplicated for this one. */
#include "fixed_layout.h"

#define NETCHESSZX_LOWRAM_MOVE_LOG_ADDR SHATRANJ_SPRINTER_LOWRAM_MOVE_LOG_ADDR
#define NETCHESSZX_LOWRAM_MOVE_LOG_SIZE SHATRANJ_SPRINTER_LOWRAM_MOVE_LOG_SIZE
#define NETCHESSZX_LOWRAM_CHAT_LOG_ADDR SHATRANJ_SPRINTER_LOWRAM_CHAT_LOG_ADDR
#define NETCHESSZX_LOWRAM_CHAT_LOG_SIZE SHATRANJ_SPRINTER_LOWRAM_CHAT_LOG_SIZE
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR SHATRANJ_SPRINTER_LOWRAM_CLOCK_SAVE_ADDR
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_SIZE SHATRANJ_SPRINTER_LOWRAM_CLOCK_SAVE_SIZE
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR SHATRANJ_SPRINTER_LOWRAM_GAME_TIMER_SAVE_ADDR
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_SIZE SHATRANJ_SPRINTER_LOWRAM_GAME_TIMER_SAVE_SIZE
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR SHATRANJ_SPRINTER_LOWRAM_LOCAL_INPUT_ADDR
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_SIZE SHATRANJ_SPRINTER_LOWRAM_LOCAL_INPUT_SIZE
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR SHATRANJ_SPRINTER_LOWRAM_INPUT_HISTORY_ADDR
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_SIZE SHATRANJ_SPRINTER_LOWRAM_INPUT_HISTORY_SIZE
#define NETCHESSZX_LOWRAM_STATUS_ADDR SHATRANJ_SPRINTER_LOWRAM_STATUS_ADDR
#define NETCHESSZX_LOWRAM_STATUS_SIZE SHATRANJ_SPRINTER_LOWRAM_STATUS_SIZE
#define NETCHESSZX_LOWRAM_STATUS_TEXT_END (SHATRANJ_SPRINTER_LOWRAM_STATUS_END - 1)
#define NETCHESSZX_LOWRAM_LAST_IP_ADDR SHATRANJ_SPRINTER_LOWRAM_LAST_IP_ADDR
#define NETCHESSZX_LOWRAM_LAST_IP_SIZE SHATRANJ_SPRINTER_LOWRAM_LAST_IP_SIZE
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR SHATRANJ_SPRINTER_LOWRAM_MQTT_PRESENCE_ADDR
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_SIZE SHATRANJ_SPRINTER_LOWRAM_MQTT_PRESENCE_SIZE
#define NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR SHATRANJ_SPRINTER_LOWRAM_CHESS_BOARD_ADDR
#define NETCHESSZX_LOWRAM_BOARD_CELL_COUNT 64u
#define NETCHESSZX_LOWRAM_RULES_BOARD_ADDR SHATRANJ_SPRINTER_LOWRAM_RULES_BOARD_ADDR
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR SHATRANJ_SPRINTER_LOWRAM_OVERLAY_CONTEXT_ADDR
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE SHATRANJ_SPRINTER_LOWRAM_OVERLAY_CONTEXT_SIZE
#define NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR SHATRANJ_SPRINTER_LOWRAM_HINTED_ROWS_ADDR
#define NETCHESSZX_LOWRAM_HINTED_ROWS_SIZE SHATRANJ_SPRINTER_LOWRAM_HINTED_ROWS_SIZE
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_ADDR SHATRANJ_SPRINTER_LOWRAM_OVERLAY_SCRATCH_ADDR
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_SIZE SHATRANJ_SPRINTER_LOWRAM_OVERLAY_SCRATCH_SIZE
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_END SHATRANJ_SPRINTER_LOWRAM_OVERLAY_SCRATCH_END
#define NETCHESSZX_LOWRAM_RENDER_SHARED_ADDR SHATRANJ_SPRINTER_LOWRAM_RENDER_SHARED_ADDR

#else /* ZX / Next: same physical 48K address space, one shared layout. */

/* 0x5b00-0x5bff: ZX printer buffer, untouched by the ROM IM1 ISR and esxDOS.
   Reclaimed for the UART RX ring (exactly 256 bytes, ends right where the
   0x5c00 sysvars the ROM ISR does touch begin). */
#define NETCHESSZX_LOWRAM_UART_RING_ADDR 0x5b00
#define NETCHESSZX_LOWRAM_UART_RING_SIZE 0x100
#define NETCHESSZX_LOWRAM_MOVE_LOG_ADDR 0x5cb6
#define NETCHESSZX_LOWRAM_MOVE_LOG_SIZE 0xe0
#define NETCHESSZX_LOWRAM_CHAT_LOG_ADDR 0x5d96
#define NETCHESSZX_LOWRAM_CHAT_LOG_SIZE 0xfc
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR 0x5e92
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_SIZE 0x08
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR 0x5e9a
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_SIZE 0x18
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR 0x5eb2
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_SIZE 0x2b
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR 0x5edd
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_SIZE 0x40
#define NETCHESSZX_LOWRAM_STATUS_ADDR 0x5f3a
#define NETCHESSZX_LOWRAM_STATUS_SIZE 0x26
#define NETCHESSZX_LOWRAM_STATUS_TEXT_END 0x5f5f
#define NETCHESSZX_LOWRAM_LAST_IP_ADDR NETCHESSZX_LOWRAM_STATUS_ADDR
#define NETCHESSZX_LOWRAM_LAST_IP_SIZE 18u
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR \
    (NETCHESSZX_LOWRAM_LAST_IP_ADDR + NETCHESSZX_LOWRAM_LAST_IP_SIZE)
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_SIZE 16u
#define NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR 0x5f60
#define NETCHESSZX_LOWRAM_BOARD_CELL_COUNT 64u
#define NETCHESSZX_LOWRAM_RULES_BOARD_ADDR 0x5fa0
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR 0x5fe0
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE 8u
#define NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR 0x5ff0
#define NETCHESSZX_LOWRAM_HINTED_ROWS_SIZE 8u

/* Shared only by the currently loaded overlay. ABOUT input and Next sprite
   staging reuse adjacent/overlapping bytes outside overlay-call lifetime;
   no overlay may retain this pointer after returning to resident code. */
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_ADDR 0x672bu
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_SIZE 160u
#define NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_END \
    (NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_ADDR + \
     NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_SIZE)

#endif /* NETCHESSZX_SPRINTER */

/* Derived *_END macros: pure arithmetic on the ADDR/SIZE pair each platform
   branch above defines, so this section is shared instead of duplicated. */
#define NETCHESSZX_LOWRAM_MOVE_LOG_END \
    (NETCHESSZX_LOWRAM_MOVE_LOG_ADDR + NETCHESSZX_LOWRAM_MOVE_LOG_SIZE)
#define NETCHESSZX_LOWRAM_CHAT_LOG_END \
    (NETCHESSZX_LOWRAM_CHAT_LOG_ADDR + NETCHESSZX_LOWRAM_CHAT_LOG_SIZE)
#define NETCHESSZX_LOWRAM_CLOCK_SAVE_END \
    (NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR + NETCHESSZX_LOWRAM_CLOCK_SAVE_SIZE)
#define NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_END \
    (NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR + \
     NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_SIZE)
#define NETCHESSZX_LOWRAM_LOCAL_INPUT_END \
    (NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR + NETCHESSZX_LOWRAM_LOCAL_INPUT_SIZE)
#define NETCHESSZX_LOWRAM_INPUT_HISTORY_END \
    (NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR + NETCHESSZX_LOWRAM_INPUT_HISTORY_SIZE)
#define NETCHESSZX_LOWRAM_STATUS_END \
    (NETCHESSZX_LOWRAM_STATUS_ADDR + NETCHESSZX_LOWRAM_STATUS_SIZE)
#define NETCHESSZX_LOWRAM_LAST_IP_END \
    (NETCHESSZX_LOWRAM_LAST_IP_ADDR + NETCHESSZX_LOWRAM_LAST_IP_SIZE)
#define NETCHESSZX_LOWRAM_MQTT_PRESENCE_END \
    (NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR + \
     NETCHESSZX_LOWRAM_MQTT_PRESENCE_SIZE)
#define NETCHESSZX_LOWRAM_CHESS_BOARD_END \
    (NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR + NETCHESSZX_LOWRAM_BOARD_CELL_COUNT)
#define NETCHESSZX_LOWRAM_RULES_BOARD_END \
    (NETCHESSZX_LOWRAM_RULES_BOARD_ADDR + NETCHESSZX_LOWRAM_BOARD_CELL_COUNT)
#define NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_END \
    (NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR + NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_SIZE)
#define NETCHESSZX_LOWRAM_HINTED_ROWS_END \
    (NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR + NETCHESSZX_LOWRAM_HINTED_ROWS_SIZE)

#ifndef NETCHESSZX_SPRINTER
/* ZX/Next-specific packing contract: these buffers alias each other to fit
   the 48K budget (LAST_IP/MQTT_PRESENCE inside STATUS, etc.). Sprinter lays
   the same buffers out back-to-back with no aliasing (see the branch above),
   so these adjacency/overlap assertions do not apply there; its own layout
   is instead proven by src/sprinter/fixed_layout.json's generic validator. */
#if (NETCHESSZX_LOWRAM_UART_RING_ADDR + NETCHESSZX_LOWRAM_UART_RING_SIZE) > 0x5c00
#error "low-RAM UART ring overlaps ROM sysvars"
#endif
#if NETCHESSZX_LOWRAM_MOVE_LOG_END > NETCHESSZX_LOWRAM_CHAT_LOG_ADDR
#error "low-RAM move log overlaps chat log"
#endif
#if NETCHESSZX_LOWRAM_CHAT_LOG_END != NETCHESSZX_LOWRAM_CLOCK_SAVE_ADDR
#error "low-RAM chat log must end at clock save"
#endif
#if NETCHESSZX_LOWRAM_CLOCK_SAVE_END != NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_ADDR
#error "low-RAM clock save must end at game timer save"
#endif
#if NETCHESSZX_LOWRAM_GAME_TIMER_SAVE_END != NETCHESSZX_LOWRAM_LOCAL_INPUT_ADDR
#error "low-RAM game timer save must end at local input"
#endif
#if NETCHESSZX_LOWRAM_LOCAL_INPUT_END > NETCHESSZX_LOWRAM_STATUS_ADDR
#error "low-RAM local input overlaps status buffer"
#endif
#if NETCHESSZX_LOWRAM_LOCAL_INPUT_END != NETCHESSZX_LOWRAM_INPUT_HISTORY_ADDR
#error "low-RAM input history must follow local input"
#endif
#if NETCHESSZX_LOWRAM_INPUT_HISTORY_END > NETCHESSZX_LOWRAM_STATUS_ADDR
#error "low-RAM input history overlaps status buffer"
#endif
#if NETCHESSZX_LOWRAM_STATUS_TEXT_END + 1 != NETCHESSZX_LOWRAM_STATUS_END
#error "low-RAM status text end must be final status byte"
#endif
#if NETCHESSZX_LOWRAM_LAST_IP_END != NETCHESSZX_LOWRAM_MQTT_PRESENCE_ADDR
#error "low-RAM last-ip must end at MQTT presence scratch"
#endif
#if NETCHESSZX_LOWRAM_MQTT_PRESENCE_END > NETCHESSZX_LOWRAM_STATUS_END
#error "low-RAM network status scratch exceeds status buffer"
#endif
#if NETCHESSZX_LOWRAM_STATUS_END != NETCHESSZX_LOWRAM_CHESS_BOARD_ADDR
#error "low-RAM status buffer must end at chess board"
#endif
#if NETCHESSZX_LOWRAM_CHESS_BOARD_END != NETCHESSZX_LOWRAM_RULES_BOARD_ADDR
#error "low-RAM chess board must end at rules board"
#endif
#if NETCHESSZX_LOWRAM_RULES_BOARD_END != NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_ADDR
#error "low-RAM rules board must end at overlay context"
#endif
#if NETCHESSZX_LOWRAM_OVERLAY_CONTEXT_END > NETCHESSZX_LOWRAM_HINTED_ROWS_ADDR
#error "low-RAM overlay context overlaps hinted rows"
#endif
#if NETCHESSZX_LOWRAM_HINTED_ROWS_END > 0x6000
#error "low-RAM hinted rows exceed reserved page"
#endif
#if NETCHESSZX_LOWRAM_OVERLAY_SCRATCH_END > 0x6800u
#error "overlay-only scratch overlaps overlay code slot"
#endif
#endif /* NETCHESSZX_SPRINTER */

#endif
