; z80 unit test for the REAL compiled MQTT reassembler.
;
; WHY THIS EXISTS. tests/sprinter/host/test_net_frame.c already exercises
; net_frame.c's nc_mqtt_* state machine, but it builds that source with gcc.
; That proves the ALGORITHM and nothing about the bytes that ship. On
; 2026-08-15 this port lost three MAME round-trips to exactly that gap: the
; host tests were green while sccz80 emitted a conditional expression that
; always took its false branch (tools/check_sccz80_codegen.py now gates that
; specific miscompile -- this file gates the behaviour regardless of which
; codegen bug causes it).
;
; So: INCBIN build/sprinter/net_frame_c.bin at its real ORG and CALL into it
; at the addresses its own .map reports (netframe_blob_defs.inc, generated by
; tools/gen_sprinter_netframe_defs.py --mode sjasmplus). The code under test
; is byte-identical to the code in SHATRANJ.EXE.
;
; Scope is deliberately the pure-memory half -- nc_mqtt_reset/feed/take/
; consume and the nc_fatal latch. nc_mqtt_pump() is not called: it dispatches
; into net_gate.asm/libman/the DLL, which this harness has no way to stand up
; (t_net_core.asm's own banner makes the same split).
;
; z88dk classic calling convention (__smallc): arguments are pushed
; left-to-right, so the FIRST argument ends up deepest; the CALLER cleans the
; stack; the return value comes back in HL.

        device  noslot64k

        org     0
        jp      start
        ds      #0100-$,0

        include "harness.inc"
        include "fixed_layout.inc"
        include "netframe_blob_defs.inc"

; The blob's own crt0 pins it to this ORG (fixed_layout.json's NET_FRAME_C
; region). Assert rather than trust: if the region ever moves, the INCBIN
; below would silently land somewhere the .map addresses do not point at.
; Deliberately a literal, not a tautology: the INCBIN below already lands at
; NET_FRAME_C_ADDR and the .map addresses come from the same build, so a move
; can never make them disagree. What this catches is a move nobody MEANT to
; make -- it has to be edited by hand, which is the point.
        assert  NET_FRAME_C_ADDR == #9880

        ds      NET_FRAME_C_ADDR-$,0
net_frame_blob:
        incbin  "net_frame_c.bin"
        assert  $ <= LOWRAM_MQTT_STREAM_ADDR

start:
        ld      sp,#e800
        call    t_begin

; --- Scenario 1: a CONNACK fed in one chunk is reassembled ---------------
; The exact bytes broker.hivemq.com answers a good CONNECT with. This is the
; packet the MQTT bring-up waits for, so if the shipped code cannot take it
; apart, the connect can never succeed no matter what the network does.
        call    blob_reset
        ld      hl,connack_bytes
        ld      b,4
        call    blob_feed

        call    nc_blob_nc_mqtt_take
        ld      a,l
        cp      4                       ; total = header 2 + remaining 2
        ld      a,1
        call    t_expect_z
        ld      a,h
        or      a                       ; and no sign/garbage in the high byte
        ld      a,2
        call    t_expect_z

; The reassembled packet must be sitting in LOWRAM_MQTT_PACKET, first byte
; 0x20 (CONNACK) and the return code byte 0 (accepted) -- the two bytes
; net_mqtt_connect_start_ovl actually tests.
        call    nc_blob_nc_mqtt_packet
        ld      de,LOWRAM_MQTT_PACKET_ADDR
        or      a
        sbc     hl,de
        ld      a,h
        or      l
        ld      a,3
        call    t_expect_z
        ld      a,(LOWRAM_MQTT_PACKET_ADDR)
        cp      #20
        ld      a,4
        call    t_expect_z
        ld      a,(LOWRAM_MQTT_PACKET_ADDR+1)
        cp      2
        ld      a,5
        call    t_expect_z
        ld      a,(LOWRAM_MQTT_PACKET_ADDR+3)
        or      a
        ld      a,6
        call    t_expect_z

; --- Scenario 2: consume leaves the stream empty, take says "not yet" ----
        ld      hl,4
        push    hl
        call    nc_blob_nc_mqtt_consume
        pop     bc
        call    nc_blob_nc_mqtt_take
        ld      a,h
        or      l
        ld      a,7
        call    t_expect_z              ; 0 = incomplete, not -1, not LINK_DOWN

; --- Scenario 3: a CONNACK split across two feeds still reassembles ------
; "split across TCP segments" is the normal case on a real link, not a
; corner case; one ng_recv poll can easily deliver a partial header.
        call    blob_reset
        ld      hl,connack_bytes
        ld      b,1
        call    blob_feed
        call    nc_blob_nc_mqtt_take
        ld      a,h
        or      l
        ld      a,8
        call    t_expect_z              ; one byte: incomplete
        ld      hl,connack_bytes+1
        ld      b,3
        call    blob_feed
        call    nc_blob_nc_mqtt_take
        ld      a,l
        cp      4
        ld      a,9
        call    t_expect_z

; --- Scenario 4: leading garbage is resynced past ------------------------
; nc_mqtt_take's allowlist has to discard bytes that cannot start a fixed
; header. A resync that ate the CONNACK instead would look exactly like the
; broker never answering.
        call    blob_reset
        ld      hl,garbage_then_connack
        ld      b,7
        call    blob_feed
        call    nc_blob_nc_mqtt_take
        ld      a,l
        cp      4
        ld      a,10
        call    t_expect_z
        ld      a,(LOWRAM_MQTT_PACKET_ADDR)
        cp      #20
        ld      a,11
        call    t_expect_z

; --- Scenario 5: the nc_fatal latch reaches nc_mqtt_take ----------------
; Empty stream + a latched peer close must report NC_LINK_DOWN (-2), which
; is what makes the CONNACK wait give up in a frame instead of grinding out
; its full ~40s timeout.
        call    blob_reset
        call    nc_blob_nc_mark_closed
        call    nc_blob_nc_mqtt_take
        ld      de,#fffe                ; -2
        or      a
        sbc     hl,de
        ld      a,h
        or      l
        ld      a,12
        call    t_expect_z

; --- Scenario 6: a complete packet still drains BEFORE LINK_DOWN --------
; A CONNACK that arrived in the same segment as the FIN must not be thrown
; away by the latch (net_frame.h's documented ordering).
        call    blob_reset
        ld      hl,connack_bytes
        ld      b,4
        call    blob_feed
        call    nc_blob_nc_mark_closed
        call    nc_blob_nc_mqtt_take
        ld      a,l
        cp      4
        ld      a,13
        call    t_expect_z              ; packet first...
        ld      hl,4
        push    hl
        call    nc_blob_nc_mqtt_consume
        pop     bc
        call    nc_blob_nc_mqtt_take
        ld      de,#fffe
        or      a
        sbc     hl,de
        ld      a,h
        or      l
        ld      a,14
        call    t_expect_z              ; ...then LINK_DOWN

; --- Scenario 7: nc_mqtt_reset clears the latch -------------------------
; The latch is SHARED with the DIRECT line splitter, so a DIRECT session
; that ended on a peer FIN leaves it set; the MQTT bring-up must be able to
; start clean or it aborts on a healthy link.
        call    blob_reset
        call    nc_blob_nc_mqtt_take
        ld      a,h
        or      l
        ld      a,15
        call    t_expect_z

        call    t_end

; --- helpers -------------------------------------------------------------
; nc_mqtt_reset() -- no arguments.
blob_reset:
        jp      nc_blob_nc_mqtt_reset

; nc_mqtt_feed(const uint8_t *data, uint8_t len): HL=data, B=len.
; __smallc pushes left-to-right and the caller cleans up.
blob_feed:
        push    hl                      ; arg 1: data
        ld      h,0
        ld      l,b
        push    hl                      ; arg 2: len
        call    nc_blob_nc_mqtt_feed
        pop     bc
        pop     bc
        ret

connack_bytes:
        db      #20,#02,#00,#00

; Bytes that cannot start a fixed header (0x00/0x11/0x7f), then a CONNACK.
garbage_then_connack:
        db      #00,#11,#7f
        db      #20,#02,#00,#00
