#!/usr/bin/env python3
"""Validate and render the Sprinter resident's fixed-address layout.

src/sprinter/fixed_layout.json is the single source of truth for the
addresses other code jumps or points to blindly: the loader's trampoline
target, the IM2 vector table/stub, and the stack/canary bounds (port.md
sections 3.1 and 3.9, rules R4/R6/R9). This tool validates the JSON against
the platform invariants and renders it into asm/sprinter/generated/
fixed_layout.inc (sjasmplus EQUs) and fixed_layout.h (C defines) so no
literal address is duplicated by hand in .asm sources.

The output is a pure function of the input JSON (no timestamps), so reruns
are byte-identical.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REQUIRED_REGIONS = ("HDR", "TRAMPOLINE", "PSP_LANDING", "CANARY", "STACK",
                     "IM2_STUB", "IM2_TABLE")
MIN_STACK_SIZE = 1024
IM2_TABLE_SIZE_REQUIRED = 0x101
GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_layout.py from "
    "src/sprinter/fixed_layout.json. Do not edit by hand."
)


class LayoutError(Exception):
    pass


def _as_int(value):
    if isinstance(value, int):
        return value
    return int(str(value), 0)


def parse_layout(raw: dict) -> dict:
    """Convert hex-string fields in the raw JSON dict to ints."""
    regions = []
    for region in raw["regions"]:
        parsed = {
            "name": region["name"],
            "addr": _as_int(region["addr"]),
            "size": _as_int(region["size"]) if "size" in region else None,
            "owner": region.get("owner", ""),
            "desc": region.get("desc", ""),
        }
        regions.append(parsed)
    return {
        "resident_base": _as_int(raw["resident_base"]),
        "win1_end": _as_int(raw["win1_end"]),
        "win2_base": _as_int(raw["win2_base"]),
        "win2_end": _as_int(raw["win2_end"]),
        "im2": {
            "fill_byte": _as_int(raw["im2"]["fill_byte"]),
            "i_reg": _as_int(raw["im2"]["i_reg"]),
        },
        "regions": regions,
    }


def _region(layout: dict, name: str):
    for region in layout["regions"]:
        if region["name"] == name:
            return region
    return None


def validate_layout(layout: dict) -> list[str]:
    """Accumulate every violation instead of failing on the first one."""
    errors: list[str] = []
    regions = layout["regions"]
    resident_base = layout["resident_base"]
    win2_end = layout["win2_end"]
    fill_byte = layout["im2"]["fill_byte"]
    i_reg = layout["im2"]["i_reg"]

    names = [r["name"] for r in regions]
    if len(names) != len(set(names)):
        dupes = sorted({n for n in names if names.count(n) > 1})
        errors.append(f"duplicate region name(s) (R9): {', '.join(dupes)}")

    for required in REQUIRED_REGIONS:
        if required not in names:
            errors.append(f"missing required region: {required}")

    if not (0 <= fill_byte <= 0xFF):
        errors.append(f"im2.fill_byte out of byte range: {fill_byte:#x}")
    if not (0 <= i_reg <= 0xFF):
        errors.append(f"im2.i_reg out of byte range: {i_reg:#x}")

    for region in regions:
        if region["addr"] < resident_base or region["addr"] >= win2_end:
            errors.append(
                f"{region['name']}: addr {region['addr']:#06x} outside "
                f"resident range {resident_base:#06x}..{win2_end:#06x}"
            )
        if region["size"] is not None and region["size"] <= 0:
            errors.append(f"{region['name']}: non-positive size {region['size']}")
        if region["size"] is not None and region["size"] > 0 \
                and region["addr"] + region["size"] > win2_end:
            errors.append(
                f"{region['name']}: end {region['addr'] + region['size']:#06x} "
                f"exceeds resident end {win2_end:#06x}"
            )

    sized = [r for r in regions if r["size"] is not None]
    sized.sort(key=lambda r: r["addr"])
    for a, b in zip(sized, sized[1:]):
        if a["addr"] + a["size"] > b["addr"]:
            errors.append(
                f"{a['name']} ({a['addr']:#06x}..{a['addr']+a['size']-1:#06x}) "
                f"overlaps {b['name']} starting at {b['addr']:#06x}"
            )
    unsized = [r for r in regions if r["size"] is None]
    for point in unsized:
        for span in sized:
            if span["addr"] <= point["addr"] < span["addr"] + span["size"]:
                errors.append(
                    f"{point['name']} at {point['addr']:#06x} falls inside "
                    f"{span['name']} ({span['addr']:#06x}..{span['addr']+span['size']-1:#06x})"
                )

    hdr = _region(layout, "HDR")
    trampoline = _region(layout, "TRAMPOLINE")
    psp_landing = _region(layout, "PSP_LANDING")
    canary = _region(layout, "CANARY")
    stack = _region(layout, "STACK")
    stub = _region(layout, "IM2_STUB")
    table = _region(layout, "IM2_TABLE")

    if hdr is not None and hdr["addr"] != resident_base:
        errors.append(
            f"HDR must start at resident_base {resident_base:#06x}, "
            f"got {hdr['addr']:#06x}"
        )
    if hdr is not None and trampoline is not None:
        hdr_end = hdr["addr"] + (hdr["size"] or 0)
        if trampoline["addr"] != hdr_end:
            errors.append(
                f"TRAMPOLINE must start right after HDR ({hdr_end:#06x}), "
                f"got {trampoline['addr']:#06x}"
            )

    if psp_landing is not None and psp_landing["addr"] != layout["win2_base"]:
        errors.append(
            f"PSP_LANDING must start at win2_base {layout['win2_base']:#06x}, "
            f"got {psp_landing['addr']:#06x}"
        )

    if canary is not None and stack is not None:
        canary_end = canary["addr"] + (canary["size"] or 0)
        if stack["addr"] != canary_end:
            errors.append(
                f"STACK must start right after CANARY ({canary_end:#06x}), "
                f"got {stack['addr']:#06x}"
            )
        if (stack["size"] or 0) < MIN_STACK_SIZE:
            errors.append(
                f"STACK size {stack['size']} below the {MIN_STACK_SIZE} byte "
                "floor (R4)"
            )

    stack_top = None
    if stack is not None and stack["size"] is not None:
        stack_top = stack["addr"] + stack["size"]
        if stub is not None and stack_top > stub["addr"]:
            errors.append(
                f"STACK_TOP {stack_top:#06x} overruns IM2_STUB at "
                f"{stub['addr']:#06x}"
            )

    if stub is not None and table is not None:
        stub_end = stub["addr"] + (stub["size"] or 0)
        if stub_end > table["addr"]:
            errors.append(
                f"IM2_STUB ({stub['addr']:#06x}..{stub_end-1:#06x}) overruns "
                f"IM2_TABLE at {table['addr']:#06x}"
            )

    if table is not None:
        if table["size"] != IM2_TABLE_SIZE_REQUIRED:
            got = "no size" if table["size"] is None else f"{table['size']:#x}"
            errors.append(
                f"IM2_TABLE size must be {IM2_TABLE_SIZE_REQUIRED:#x} "
                f"(257, one word per vector byte incl. the 0xFF straddle), "
                f"got {got}"
            )
        if table["addr"] % 256 != 0:
            errors.append(f"IM2_TABLE addr {table['addr']:#06x} is not 256-aligned")
        if (table["addr"] >> 8) & 0xFF != i_reg:
            errors.append(
                f"im2.i_reg {i_reg:#04x} must equal the high byte of "
                f"IM2_TABLE addr {table['addr']:#06x}"
            )
        if table["size"] is not None and table["addr"] + table["size"] > win2_end:
            errors.append(
                f"IM2_TABLE end {table['addr']+table['size']:#06x} exceeds "
                f"WIN2 end {win2_end:#06x}"
            )

    if stub is not None:
        derived_stub = (fill_byte * 0x101) & 0xFFFF
        if stub["addr"] != derived_stub:
            errors.append(
                "IM2_STUB addr must equal im2.fill_byte * 0x101 (the "
                f"identical-fill-byte trick): fill_byte {fill_byte:#04x} "
                f"implies {derived_stub:#06x}, got {stub['addr']:#06x}"
            )

    return errors


def compute_symbols(layout: dict) -> dict:
    symbols = {}
    for region in layout["regions"]:
        name = region["name"]
        symbols[f"{name}_ADDR"] = region["addr"]
        if region["size"] is not None:
            symbols[f"{name}_SIZE"] = region["size"]
            symbols[f"{name}_END"] = region["addr"] + region["size"]
    stack = _region(layout, "STACK")
    symbols["STACK_TOP"] = stack["addr"] + stack["size"]
    symbols["TRAMPOLINE_ADDR"] = _region(layout, "TRAMPOLINE")["addr"]
    symbols["RESIDENT_BASE"] = layout["resident_base"]
    symbols["WIN1_END"] = layout["win1_end"]
    symbols["WIN2_BASE"] = layout["win2_base"]
    symbols["WIN2_END"] = layout["win2_end"]
    symbols["IM2_FILL_BYTE"] = layout["im2"]["fill_byte"]
    symbols["IM2_I_REG"] = layout["im2"]["i_reg"]
    return symbols


def render_inc(symbols: dict) -> str:
    guard = "SPRINTER_FIXED_LAYOUT_INC"
    lines = [
        f"; {GENERATED_BANNER}",
        "",
        f"        IFNDEF {guard}",
        f"        DEFINE {guard}",
        "",
    ]
    for name in sorted(symbols):
        value = symbols[name]
        width = 4 if value > 0xFF else 2
        lines.append(f"{name:<20} EQU #{value:0{width}X}")
    lines.append("")
    lines.append("        ENDIF")
    lines.append("")
    return "\n".join(lines)


def render_h(symbols: dict) -> str:
    guard = "SHATRANJ_SPRINTER_FIXED_LAYOUT_H"
    lines = [
        f"/* {GENERATED_BANNER} */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    for name in sorted(symbols):
        value = symbols[name]
        lines.append(f"#define SHATRANJ_SPRINTER_{name} 0x{value:04X}")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def load_layout_file(path: Path) -> dict:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return parse_layout(raw)


# ---------------------------------------------------------------------------
# Self-test: a clean fixture must validate, and each fixture with exactly one
# invariant deliberately broken must be rejected (tools/check_*.py pattern).
# ---------------------------------------------------------------------------

def _clean_fixture() -> dict:
    raw = {
        "resident_base": "0x4000",
        "win1_end": "0x8000",
        "win2_base": "0x8000",
        "win2_end": "0xC000",
        "im2": {"fill_byte": "0xBD", "i_reg": "0xBE"},
        "regions": [
            {"name": "HDR", "addr": "0x4000", "size": "0x100"},
            {"name": "TRAMPOLINE", "addr": "0x4100"},
            {"name": "PSP_LANDING", "addr": "0x8000", "size": "0x100"},
            {"name": "CANARY", "addr": "0xB900", "size": "0x2"},
            {"name": "STACK", "addr": "0xB902", "size": "0x47E"},
            {"name": "IM2_STUB", "addr": "0xBDBD", "size": "0xF"},
            {"name": "IM2_TABLE", "addr": "0xBE00", "size": "0x101"},
        ],
    }
    return parse_layout(raw)


def self_test() -> None:
    clean = _clean_fixture()
    errors = validate_layout(clean)
    if errors:
        raise SystemExit(
            "[ERR] layout self-test: clean fixture rejected: " + "; ".join(errors)
        )
    symbols = compute_symbols(clean)
    if symbols["STACK_TOP"] != 0xBD80:
        raise SystemExit("[ERR] layout self-test: STACK_TOP derivation wrong")
    inc1 = render_inc(symbols)
    inc2 = render_inc(compute_symbols(_clean_fixture()))
    if inc1 != inc2:
        raise SystemExit("[ERR] layout self-test: .inc rendering is not deterministic")

    def broken(mutate):
        fixture = _clean_fixture()
        mutate(fixture)
        return fixture

    # Each case pins the specific diagnostic it is meant to trip: a broken
    # fixture often violates several invariants at once (e.g. moving the
    # table also breaks i_reg), so "any error" would let individual checks
    # be deleted without the self-test noticing.
    cases = {
        "short stack (R4)": (
            lambda f: _region(f, "STACK").__setitem__("size", 512),
            "below the",
        ),
        "misaligned table": (
            lambda f: _region(f, "IM2_TABLE").__setitem__("addr", 0xBE01),
            "not 256-aligned",
        ),
        "stub != fill_byte*0x101": (
            lambda f: _region(f, "IM2_STUB").__setitem__("addr", 0xBDBC),
            "fill_byte",
        ),
        "table size != 257": (
            lambda f: _region(f, "IM2_TABLE").__setitem__("size", 0x100),
            "size must be",
        ),
        "table without a size": (
            lambda f: _region(f, "IM2_TABLE").__setitem__("size", None),
            "size must be",
        ),
        "i_reg mismatch": (
            lambda f: f["im2"].__setitem__("i_reg", 0xBF),
            "high byte",
        ),
        "table beyond WIN2": (
            lambda f: _region(f, "IM2_TABLE").__setitem__("addr", 0xBF00),
            "exceeds",
        ),
        "oversized region past resident end": (
            lambda f: f["regions"].append(
                {"name": "X", "addr": 0xBF10, "size": 0x2000,
                 "owner": "", "desc": ""}
            ),
            "exceeds resident end",
        ),
        "duplicate region name": (
            lambda f: f["regions"].append(dict(_region(f, "STACK"))),
            "duplicate",
        ),
        "overlapping regions": (
            lambda f: _region(f, "CANARY").__setitem__("size", 0x10),
            "overlaps",
        ),
        "missing required region": (
            lambda f: f["regions"].remove(_region(f, "IM2_STUB")),
            "missing required region",
        ),
        "HDR not at resident_base": (
            lambda f: _region(f, "HDR").__setitem__("addr", 0x4010),
            "must start at resident_base",
        ),
        "trampoline gap after HDR": (
            lambda f: _region(f, "TRAMPOLINE").__setitem__("addr", 0x4200),
            "right after HDR",
        ),
        "psp_landing not at win2_base": (
            lambda f: _region(f, "PSP_LANDING").__setitem__("addr", 0x8100),
            "must start at win2_base",
        ),
    }
    for label, (mutate, needle) in cases.items():
        fixture = broken(mutate)
        errors = validate_layout(fixture)
        if not any(needle in error for error in errors):
            raise SystemExit(
                f"[ERR] layout self-test: broken fixture not rejected with "
                f"the expected diagnostic ({label}: wanted {needle!r}, "
                f"got {errors})"
            )

    print("[OK] Sprinter fixed-layout self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", type=Path,
                        default=Path("src/sprinter/fixed_layout.json"))
    parser.add_argument("--inc-out", type=Path)
    parser.add_argument("--h-out", type=Path)
    parser.add_argument("--check", action="store_true",
                        help="validate only, do not write output files")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    layout = load_layout_file(args.layout)
    errors = validate_layout(layout)
    if errors:
        print(f"[ERR] {args.layout}: fixed-layout invariants violated")
        for error in errors:
            print(f"  {error}")
        return 1

    if args.check:
        print(f"[OK] {args.layout}: fixed-layout invariants hold")
        return 0

    if not args.inc_out or not args.h_out:
        raise SystemExit("gen_sprinter_layout: --inc-out and --h-out are required "
                          "unless --check or --self-test is given")

    symbols = compute_symbols(layout)
    args.inc_out.parent.mkdir(parents=True, exist_ok=True)
    args.h_out.parent.mkdir(parents=True, exist_ok=True)
    args.inc_out.write_text(render_inc(symbols), encoding="ascii")
    args.h_out.write_text(render_h(symbols), encoding="ascii")
    print(f"[OK] {args.inc_out}")
    print(f"[OK] {args.h_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
