#!/usr/bin/env python3
"""Bridge the WIN3 cold page's render entry points into sjasmplus EQUs for
tests/sprinter/z80/t_hint_blit.asm.

That test INCBINs build/sprinter/cold_win3_page.bin at its real ORG and CALLs
into it, so it needs the addresses from that image's OWN .map
(build/sprinter/cold_page_image.map) -- nothing the WIN1 resident build
produces can see them. Same role tools/gen_sprinter_netframe_defs.py plays
for the WIN2 blob and tools/gen_sprinter_platform_defs.py plays for the
resident primitives, and the same contract: the output is a pure function of
the input .map (no timestamps), so reruns are byte-identical.

The allowlist is deliberately tiny -- only what the blit test drives. It is
NOT a general cold-page bridge: the cold page is at its size ceiling and
nothing in the shipping build may grow a dependency on this file.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Symbols t_hint_blit.asm calls or inspects. render_hint_marker is the entry
# under test; the frame_* / draw_frame_at_slot cells are what the test reads
# back to prove draw_frame_at_sized handed the blitter the right parameters.
COLD_RENDER_SYMBOLS = [
    "render_hint_marker",
    "render_cursor_marker",
    "draw_frame_at_slot",
    "frame_tw",
    "frame_th",
    "frame_ox",
    "frame_oy",
    "_spectrum_gui_board_flipped",
    "_netchesszx_movement_hints",
    # S9 About, second MAME round: what tests/sprinter/z80/t_about_restore.asm
    # drives and intercepts while running the shipped about_restore_screen.
    # The entry under test, then every paint it is supposed to reach -- the
    # test replaces each one with a recorder and asserts the resulting call
    # log. The WIN1/WIN2 addresses among them (video_init, net_status_idle)
    # come from this same map: the cold page reaches them through generated
    # defc bridges, so its .map carries them alongside its own symbols.
    "_about_restore_screen",
    "video_clear_both_buffers",
    "_video_init",
    "_spectrum_gui_restore_board_area",
    "_render_coord_labels",
    "render_banner",
    "render_menu_bar",
    "render_status_text",
    "render_input_line",
    "_spectrum_info_show_game",
    "_spectrum_render_moves",
    "_spectrum_render_chat",
    "_spectrum_render_clock",
    "_spectrum_render_game_timer_clear",
    "_spectrum_render_notice",
    "_spectrum_gui_set_connected",
    "_spectrum_gui_set_turn_label",
    "_net_status_idle",
    # State the test seeds so the run takes one determinate path through
    # gui.c, plus the modal gate it checks was lowered.
    "_net_active",
    "_about_visible",
    "_menu_visible",
    "_notice_error",
    "_notice_success",
]

# From build/sprinter/platform_primitives.sym (sjasmplus "name: EQU 0x..."):
# the shared tile parameter block gfx_draw_tile reads, plus the two page/
# buffer cells draw_frame_at consults. The blit test inspects these to see
# what render_hint_marker actually handed the blitter.
PLATFORM_SYMBOLS = [
    # S9 About pass: what tests/sprinter/z80/t_about_blit.asm stubs and
    # inspects while running the shipped ABOUT overlay.
    "about_page0",
    "palette_apply_from",
    "text_print",
    "flip_mark_dirty_all",
    "bench_asset_page",
    "back_base",
    "gfx_draw_tile",
    "gfx_blit_rows",
    "gfx_fill_rect",
    "tile_src_page",
    "tile_src_slot",
    "tile_x_byte",
    "tile_x_hi",
    "tile_y",
    "tile_stride",
    "tile_width",
    "tile_rows",
    "tile_alias",
]

MAP_LINE = re.compile(r"^(\S+)\s+=\s+\$([0-9A-Fa-f]+)\b")
SYM_LINE = re.compile(r"^(\S+?):\s+EQU\s+0x([0-9A-Fa-f]+)\b")


def parse_sym(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in text.splitlines():
        m = SYM_LINE.match(line.strip())
        if m:
            out.setdefault(m.group(1), int(m.group(2), 16))
    return out


def parse_map(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in text.splitlines():
        m = MAP_LINE.match(line.strip())
        if m:
            out.setdefault(m.group(1), int(m.group(2), 16))
    return out


def render(symbols: dict[str, int],
            plat: dict[str, int] | None = None) -> str:
    missing = [n for n in COLD_RENDER_SYMBOLS if n not in symbols]
    if missing:
        raise SystemExit(
            "Error: cold_page_image.map is missing symbol(s): "
            + ", ".join(sorted(missing))
        )
    plat = plat or {}
    plat_missing = [n for n in PLATFORM_SYMBOLS if n not in plat]
    if plat and plat_missing:
        raise SystemExit(
            "Error: platform_primitives.sym is missing symbol(s): "
            + ", ".join(sorted(plat_missing))
        )
    lines = [
        "; Generated by tools/gen_sprinter_coldrender_defs.py -- do not edit.",
        "; Source: build/sprinter/cold_page_image.map (the WIN3 cold page).",
    ]
    for name in COLD_RENDER_SYMBOLS:
        # sjasmplus has no leading-underscore restriction, but the z88dk map
        # spells C-visible symbols with one; keep the name verbatim so the
        # test refers to exactly what the map says.
        lines.append(f"{name}: EQU 0x{symbols[name]:08X}")
    if plat:
        lines.append("; From build/sprinter/platform_primitives.sym:")
        for name in PLATFORM_SYMBOLS:
            lines.append(f"{name}: EQU 0x{plat[name]:08X}")
    return "\n".join(lines) + "\n"


def self_test() -> int:
    # Both fixtures are derived from the allowlists, not hand-written: each
    # list grows every time a test needs another symbol, and a literal table
    # here would break on every addition without saying anything useful
    # about the generator.
    fixture = "".join(
        f"{n}{' ' * max(1, 32 - len(n))}= ${0xC100 + i:04X} ; addr, public\n"
        for i, n in enumerate(COLD_RENDER_SYMBOLS)
    )
    sym_fixture = "".join(
        f"{n}: EQU 0x0000{0x8200 + i:04X}\n"
        for i, n in enumerate(PLATFORM_SYMBOLS)
    )
    out = render(parse_map(fixture), parse_sym(sym_fixture))
    for probe in ("render_hint_marker", "frame_oy", "_about_restore_screen"):
        expect = 0xC100 + COLD_RENDER_SYMBOLS.index(probe)
        assert f"{probe}: EQU 0x{expect:08X}" in out, out
    expect = 0x8200 + PLATFORM_SYMBOLS.index("tile_src_slot")
    assert f"tile_src_slot: EQU 0x{expect:08X}" in out, out
    assert render(parse_map(fixture), parse_sym(sym_fixture)) == out, \
        "not deterministic"
    # A map missing one of the required names must fail loudly, not emit a
    # file the test would then fail to assemble.
    try:
        render(parse_map("render_hint_marker = $F32A ; addr, public\n"))
    except SystemExit:
        pass
    else:  # pragma: no cover
        raise AssertionError("incomplete map was accepted")
    # A sym file missing one of the required names must fail loudly rather
    # than silently emitting a file the test would then fail to assemble.
    try:
        render(parse_map(fixture), parse_sym("bench_asset_page: EQU 0x8656\n"))
    except SystemExit:
        pass
    else:  # pragma: no cover
        raise AssertionError("incomplete sym file was accepted")
    print("[OK] Sprinter cold-render defs self-test")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--map", type=Path)
    ap.add_argument("--sym", type=Path)
    ap.add_argument("--out", type=Path)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    if not args.map or not args.out:
        ap.error("--map and --out are required unless --self-test")
    plat = parse_sym(args.sym.read_text()) if args.sym else {}
    text = render(parse_map(args.map.read_text()), plat)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"[OK] {args.out}: cold-page render defs written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
