#!/usr/bin/env python3
"""Bridge the WIN1 resident C image's symbols into the WIN3 cold-code page.

The mirror image of tools/gen_sprinter_cold_thunks.py: that tool lets WIN1
call into the cold page, this one lets the cold page call back out. Both
directions are needed because the page holds whole modules now, not leaf
routines -- src/spectrum/ui/gui.c lives there and calls the frame/key
shims, src/spectrum/platform/text.c and the session config, all of which
stay resident.

No window juggling is involved in THIS direction, which is why it is only
a defc table and not a thunk: WIN1 is always mapped, so cold-page code
reaches a resident routine with a plain `call`. What it cannot do is
resolve the address at compile time on its own -- hence the same
map-reading shape as gen_sprinter_overlay_defs.py (resident_c.map ->
overlay C) and gen_sprinter_netframe_defs.py (net_frame_c.map -> resident
C).

This is what fixed the build order: the cold page is built AFTER
resident_c.bin so this map exists, which is possible only because the
thunks in the other direction stopped needing the cold page's own map (see
gen_sprinter_cold_thunks.py's banner on the fixed entry table).

The output is a pure function of the input .map file (no timestamps), so
reruns are byte-identical -- same contract as the other gen_sprinter_*
tools.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Curated allowlist: only these resident symbols are visible to cold-page
# code. Adding a new cross-boundary call means adding its name here -- same
# discipline as OVERLAY_RESIDENT_SYMBOLS/PLATFORM_SYMBOLS/COLD_THUNK_SYMBOLS.
#
# A name here must NOT also be in COLD_THUNK_SYMBOLS: that would mean the
# same routine is claimed by both images, and the defc would silently win
# inside the page while WIN1 called the thunk. gen_sprinter_cold_thunks.py
# imports this list and the self-test below asserts the two are disjoint.
COLD_RESIDENT_SYMBOLS = [
    # render_shim.asm -- the three per-frame bridges deliberately left in
    # WIN1 because a thunk would cost more than the routine (1-9 byte
    # bodies). All three are exactly what gui.c reaches back for.
    "spectrum_frame_wait",
    "spectrum_key_poll",
    "spectrum_uart_background_pump",
    # src/common/chess/move_coords.c -- gui.c's move-log coordinate parse.
    "netchesszx_move_parse_coords",
    # src/spectrum/config/session.c -- a plain data byte, not a call. Safe
    # to read from the page for the same reason the calls above are safe to
    # make: WIN1 never leaves the address space, only WIN3 changes.
    "netchesszx_movement_hints",
]

GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_cold_defs.py from the resident C "
    "image's .map file. Do not edit by hand."
)

# z88dk map lines: "_name    = $ADDR ; addr, public, ...". C symbols always
# carry the leading underscore z88dk adds; the allowlist omits it (to read
# the same as the C source) and this parser strips it back off.
MAP_LINE = re.compile(r"^_(\S+)\s+=\s+\$([0-9A-Fa-f]+)\s*;")

# The WIN1 resident C image's window. A symbol outside it is not something
# the cold page can call with WIN3 mapped to itself.
RESIDENT_LO = 0x4000
RESIDENT_HI = 0xBFFF


class ColdDefsError(Exception):
    pass


def parse_map(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = MAP_LINE.match(line.strip())
            if match:
                symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def render(symbols: dict[str, int], names: list[str]) -> str:
    missing = [name for name in names if name not in symbols]
    if missing:
        raise ColdDefsError(
            "missing resident symbol(s) (add to SPRINTER_RESIDENT_C_SRC or "
            "drop from COLD_RESIDENT_SYMBOLS): " + ", ".join(missing)
        )
    outside = [
        name for name in names
        if not RESIDENT_LO <= symbols[name] <= RESIDENT_HI
    ]
    if outside:
        raise ColdDefsError(
            "resident symbol(s) outside the always-mapped WIN1/WIN2 range "
            f"#{RESIDENT_LO:04X}-#{RESIDENT_HI:04X} (the cold page cannot "
            "reach those with itself mapped into WIN3): "
            + ", ".join(f"{n}=${symbols[n]:04X}" for n in outside)
        )
    lines = [
        f";; {GENERATED_BANNER}",
        ";; z88dk-z80asm syntax (linked into the WIN3 cold-code page "
        "alongside src/spectrum/ui/gui.c)",
        "",
    ]
    for name in names:
        addr = symbols[name]
        lines.append(f"PUBLIC _{name}")
        lines.append(f"defc _{name} = ${addr:04X}")
        lines.append(f"PUBLIC {name}")
        lines.append(f"defc {name} = ${addr:04X}")
    lines.append("")
    return "\n".join(lines)


def _clean_fixture() -> str:
    lines = []
    addr = 0x7100
    for name in COLD_RESIDENT_SYMBOLS:
        lines.append(
            f"_{name:<32} = ${addr:04X} ; addr, public, , "
            "render_shim, code_user, "
            "asm/sprinter/zcc/render_shim.asm:1\n"
        )
        addr += 0x20
    lines.append(
        "i_7                              = $7100 ; addr, local, , "
        "src_spectrum_board_board_c, code_compiler, "
        "src/spectrum/board/board.c::whatever::0::0:1\n"
    )
    return "".join(lines)


def self_test() -> None:
    import tempfile

    import gen_sprinter_cold_thunks as thunks

    both = sorted(set(COLD_RESIDENT_SYMBOLS) & set(thunks.COLD_THUNK_SYMBOLS))
    if both:
        raise SystemExit(
            "[ERR] cold-defs self-test: symbol(s) claimed by BOTH images "
            "(a cold-page thunk and a resident defc): " + ", ".join(both)
        )

    with tempfile.TemporaryDirectory() as tmp:
        map_path = Path(tmp) / "clean.map"
        map_path.write_text(_clean_fixture(), encoding="ascii")
        symbols = parse_map(map_path)

        if symbols.get("spectrum_frame_wait") != 0x7100:
            raise SystemExit("[ERR] cold-defs self-test: symbol not parsed")
        if "i_7" in symbols:
            raise SystemExit("[ERR] cold-defs self-test: local label wrongly captured")

        out1 = render(symbols, COLD_RESIDENT_SYMBOLS)
        out2 = render(symbols, COLD_RESIDENT_SYMBOLS)
        if out1 != out2:
            raise SystemExit("[ERR] cold-defs self-test: rendering is not deterministic")
        if "defc _spectrum_frame_wait = $7100" not in out1:
            raise SystemExit("[ERR] cold-defs self-test: underscored defc missing")
        if "defc spectrum_frame_wait = $7100" not in out1:
            raise SystemExit("[ERR] cold-defs self-test: asm-facing defc missing")

        try:
            render(symbols, COLD_RESIDENT_SYMBOLS + ["totally_missing"])
        except ColdDefsError as exc:
            if "totally_missing" not in str(exc):
                raise SystemExit(
                    "[ERR] cold-defs self-test: wrong missing-symbol diagnostic"
                )
        else:
            raise SystemExit(
                "[ERR] cold-defs self-test: missing symbol was not rejected"
            )

        # A resident symbol that somehow resolved into the WIN3 window is
        # the one mistake that would link cleanly and then call itself.
        try:
            render({"spectrum_frame_wait": 0xC123}, ["spectrum_frame_wait"])
        except ColdDefsError as exc:
            if "outside the always-mapped" not in str(exc):
                raise SystemExit(
                    "[ERR] cold-defs self-test: wrong out-of-range diagnostic"
                )
        else:
            raise SystemExit(
                "[ERR] cold-defs self-test: WIN3-range address was not rejected"
            )

    print("[OK] Sprinter cold-defs self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path, help="resident_c.map to read")
    parser.add_argument("--out", type=Path, help="cold_defs.asm to write")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        self_test()
        return 0

    if not args.map or not args.out:
        raise SystemExit(
            "gen_sprinter_cold_defs: --map and --out are required unless --self-test"
        )

    symbols = parse_map(args.map)
    try:
        text = render(symbols, COLD_RESIDENT_SYMBOLS)
    except ColdDefsError as exc:
        print(f"[ERR] {args.map}: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="ascii")
    print(f"[OK] {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
