#!/usr/bin/env python3
"""Bridge net_frame.c's WIN2 C-blob symbol table into z88dk-linkable defc's.

net_frame.c (src/sprinter/transport/net_frame.c, S7/port.md section 3.7) is
built as its own independent zcc program -- asm/sprinter/zcc/net_core_crt0.
asm at a fixed ORG (fixed_layout.json's NET_FRAME_C region), spliced into
the flat resident image by tools/make_sprinter_resident.py the same way
platform_primitives.bin already is. Its compiled address is therefore only
known from ITS OWN .map file, not from anything the WIN1 resident C build
(src/sprinter/main.c + friends) can see directly.

This tool is the mirror of tools/gen_sprinter_overlay_defs.py (which bridges
resident_c.map -> overlay C sources) and tools/gen_sprinter_platform_defs.py
(which bridges platform_primitives.sym -> resident C): here the source is
net_frame_c.map (z88dk's own map format, same shape as resident_c.map) and
the consumer is the WIN1 resident C build itself -- src/sprinter/transport/
unet_link.c calls nc_* functions across this same "fixed address, no
shared link unit" boundary net_gate.asm's ng_* routines already cross (via
gen_sprinter_platform_defs.py), just compiled by zcc instead of sjasmplus.

The output is a pure function of the input .map file (no timestamps), so
reruns are byte-identical -- same contract as the other two gen_sprinter_*
tools.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Curated allowlist: only these net_frame.c symbols are exposed to the WIN1
# resident C build. Adding a new cross-boundary call means adding its name
# here -- same discipline as OVERLAY_RESIDENT_SYMBOLS/PLATFORM_SYMBOLS
# elsewhere. nc_smoke is step 1's build-pipeline proof; step 2 adds the
# portable line-framing core's real entry points (src/sprinter/transport/
# unet_link.c, step 3, calls these directly -- nc_pump itself, the target-
# only backend glue around ng_recv, is added in step 3, not here).
NETFRAME_RESIDENT_SYMBOLS = [
    "nc_smoke",
    "nc_init",
    "nc_feed",
    "nc_line_pop",
    "nc_mark_closed",
    "nc_mark_lost",
    "nc_queue_count",
    # step 3: the ng_recv-polling glue itself, called from WIN1's
    # background_drain (src/sprinter/transport/unet_link.c).
    "nc_pump",
]

GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_netframe_defs.py from net_frame.c's "
    "own .map file. Do not edit by hand."
)

# z88dk map lines: "_name    = $ADDR ; addr, public, ...". C symbols always
# carry the leading underscore z88dk adds; the allowlist above omits it (to
# read the same as the C source) and this parser strips it back off so both
# sides agree on one canonical (unprefixed) key.
MAP_LINE = re.compile(r"^_(\S+)\s+=\s+\$([0-9A-Fa-f]+)\s*;")


class NetframeDefsError(Exception):
    pass


def parse_map(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = MAP_LINE.match(line.strip())
            if match:
                symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def render(symbols: dict[str, int], names: list[str]) -> str:
    missing = [name for name in names if name not in symbols]
    if missing:
        raise NetframeDefsError(
            "missing net_frame.c symbol(s) (add to src/sprinter/transport/"
            "net_frame.c or drop from NETFRAME_RESIDENT_SYMBOLS): "
            + ", ".join(missing)
        )
    lines = [f";; {GENERATED_BANNER}",
             ";; z88dk-z80asm syntax (consumed by the WIN1 resident C "
             "build, e.g. src/sprinter/transport/unet_link.c)",
             ""]
    for name in names:
        addr = symbols[name]
        lines.append(f"PUBLIC _{name}")
        lines.append(f"defc _{name} = ${addr:04X}")
    lines.append("")
    return "\n".join(lines)


def _clean_fixture() -> str:
    return (
        "_nc_smoke                       = $9D00 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_smoke::0::0:6\n"
        "i_2                             = $9D00 ; addr, local, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_smoke::0::0:6\n"
        "_nc_init                        = $9D10 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_init::0::0:6\n"
        "_nc_feed                        = $9D30 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_feed::0::0:6\n"
        "_nc_line_pop                    = $9D80 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_line_pop::0::0:6\n"
        "_nc_mark_closed                 = $9DC0 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_mark_closed::0::0:6\n"
        "_nc_mark_lost                   = $9DC8 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_mark_lost::0::0:6\n"
        "_nc_queue_count                 = $9DD0 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_queue_count::0::0:6\n"
        "_nc_pump                        = $9FA1 ; addr, public, , "
        "src_sprinter_transport_net_frame_c, code_compiler, "
        "src/sprinter/transport/net_frame.c::nc_pump::0::21:143\n"
    )


def self_test() -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        map_path = Path(tmp) / "clean.map"
        map_path.write_text(_clean_fixture(), encoding="ascii")
        symbols = parse_map(map_path)

        if symbols.get("nc_smoke") != 0x9D00:
            raise SystemExit("[ERR] netframe-defs self-test: function symbol not parsed")
        if "i_2" in symbols:
            raise SystemExit("[ERR] netframe-defs self-test: local label wrongly captured")

        out1 = render(symbols, NETFRAME_RESIDENT_SYMBOLS)
        out2 = render(symbols, NETFRAME_RESIDENT_SYMBOLS)
        if out1 != out2:
            raise SystemExit("[ERR] netframe-defs self-test: rendering is not deterministic")
        if "PUBLIC _nc_smoke" not in out1:
            raise SystemExit("[ERR] netframe-defs self-test: underscored name missing")
        if "defc _nc_smoke = $9D00" not in out1:
            raise SystemExit("[ERR] netframe-defs self-test: address mismatch")

        try:
            render(symbols, NETFRAME_RESIDENT_SYMBOLS + ["totally_missing"])
        except NetframeDefsError as exc:
            if "totally_missing" not in str(exc):
                raise SystemExit(
                    "[ERR] netframe-defs self-test: wrong missing-symbol diagnostic"
                )
        else:
            raise SystemExit(
                "[ERR] netframe-defs self-test: missing symbol was not rejected"
            )

    print("[OK] Sprinter netframe-defs self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path, help="net_frame_c.map to read")
    parser.add_argument("--out", type=Path, help="netframe_defs.asm to write")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    if not args.map or not args.out:
        raise SystemExit(
            "gen_sprinter_netframe_defs: --map and --out are required unless --self-test"
        )

    symbols = parse_map(args.map)
    try:
        text = render(symbols, NETFRAME_RESIDENT_SYMBOLS)
    except NetframeDefsError as exc:
        print(f"[ERR] {args.map}: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="ascii")
    print(f"[OK] {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
