#!/usr/bin/env python3
"""Validate and render the Sprinter render core's semantic palette.

assets/sprinter/palette.json is the single source of truth for the 16-entry
mode #82 palette (port.md section 3.5): the base RGB8 triples for indices
0-15, the theme table that overrides indices 2/3 (light/dark board square)
and the per-set piece palettes that override 4-7 -- both for an instant,
tile-traffic-free switch, since the tiles store indices rather than
colours. This tool renders that JSON into independent outputs, keeping
every consumer -- the boot palette, the theme table, the piece-tile
packer's per-set colours, and the piece rasterizer's quantization targets
-- reading the same numbers:

  - asm/sprinter/generated/palette_base.inc: the 16x3-byte palette_rgb
    table asm/sprinter/video_s1.asm INCLUDEs (replacing its old ad-hoc EGA
    ramp).
  - asm/sprinter/generated/piece_set_palettes.inc (render_piece_sets_inc):
    the per-set 4-colour records. Written on demand via
    --piece-sets-inc-out; its Z80 consumer arrives with the set-selection
    UI (port.md stage S14), so the build does not generate it yet.
  - a binary theme-table blob (build_theme_blob) packed into the assets
    page at slot 27 by tools/make_sprinter_assets_page.py's --theme-bin.
    NOTE: no shipped code reads that blob. It was S4's scene demo's theme
    source; the resident's own themes are asm/sprinter/video.asm's
    hand-written theme_squares_rgb, which this file's "themes" mirror
    verbatim under a test that parses the .asm back out.
    Format v1: byte 0 = format (1), byte 1 = theme count, byte 2 = entries
    per theme E, byte 3 = reserved (0), then per theme: 8-byte ASCII
    NUL-padded name, then E x (palette index, R, G, B).

    The name field is 8 bytes but a name may use at most 7 of them: the
    Z80 side (asm/sprinter/scene_s4.asm's scene_draw_status) prints the
    field IN PLACE as an ASCIIZ string, so the 8th byte has to be the
    terminator. A full-width 8-character name would run the status-bar
    text renderer straight into the following record's entry bytes.

Index 15 is an ordinary colour like any other -- the hardware transparency
key is a per-tile property of data drawn through the keyed VRAM alias, not
a global palette reservation (port.md section 3.5, amended when S4 closed).

The outputs are a pure function of the input JSON (no timestamps), so
reruns are byte-identical.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REQUIRED_BASE_COUNT = 16
THEMEABLE_INDICES = {2, 3, 8, 9, 10}
# The four entries a piece SET owns. They are to a set what 2/3 are to a
# theme: the tiles store indices, so switching sets re-writes four palette
# registers and repaints nothing (port.md section 3.5).
PIECE_SET_INDICES = frozenset({4, 5, 6, 7})
MIN_PIECE_SET_COUNT = 1
MAX_PIECE_SET_COUNT = 8
# Blob field width vs. usable characters: the last byte must stay NUL so
# the field is a valid ASCIIZ string where the Z80 prints it (see the
# module docstring).
THEME_NAME_FIELD_LEN = 8
MAX_THEME_NAME_LEN = THEME_NAME_FIELD_LEN - 1
MIN_THEME_COUNT = 1
MAX_THEME_COUNT = 8
MIN_THEME_ENTRIES = 1
GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_palette.py from "
    "assets/sprinter/palette.json. Do not edit by hand."
)

_HEX_RE = re.compile(r"^#([0-9A-Fa-f]{6})$")


def _parse_rgb(value: str, where: str) -> tuple[int, int, int]:
    m = _HEX_RE.match(value)
    if not m:
        raise ValueError(f"{where}: invalid RGB hex string {value!r} (want #RRGGBB)")
    hex6 = m.group(1)
    return int(hex6[0:2], 16), int(hex6[2:4], 16), int(hex6[4:6], 16)


def parse_palette(raw: dict) -> dict:
    base = [
        {
            "index": int(entry["index"]),
            "name": entry["name"],
            "rgb": entry["rgb"],
        }
        for entry in raw["base"]
    ]
    themes = [
        {
            "name": theme["name"],
            "entries": {str(k): v for k, v in theme["entries"].items()},
        }
        for theme in raw["themes"]
    ]
    piece_sets = [
        {
            "name": entry["name"],
            "entries": {str(k): v for k, v in entry["entries"].items()},
        }
        for entry in raw.get("piece_sets", [])
    ]
    return {"base": base, "themes": themes, "piece_sets": piece_sets}


def validate_palette(palette: dict) -> list[str]:
    errors: list[str] = []
    base = palette["base"]
    themes = palette["themes"]

    indices_seen: dict[int, int] = {}
    base_rgb: dict[int, tuple[int, int, int]] = {}
    for entry in base:
        idx = entry["index"]
        indices_seen[idx] = indices_seen.get(idx, 0) + 1
        if not (0 <= idx < REQUIRED_BASE_COUNT):
            errors.append(f"base index {idx} out of range 0..{REQUIRED_BASE_COUNT - 1}")
            continue
        # The name ends up as an ASCII comment in the generated .inc, which
        # is written with encoding="ascii" -- reject non-ASCII here so it
        # surfaces as an [ERR] diagnostic naming the entry instead of a raw
        # UnicodeEncodeError traceback out of render_inc.
        name = entry["name"]
        if not isinstance(name, str) or not name:
            errors.append(f"base index {idx}: name must be a non-empty string")
        else:
            try:
                name.encode("ascii")
            except UnicodeEncodeError:
                errors.append(f"base index {idx}: name {name!r} is not pure ASCII")
        try:
            base_rgb[idx] = _parse_rgb(entry["rgb"], f"base index {idx}")
        except ValueError as exc:
            errors.append(str(exc))

    for idx, count in indices_seen.items():
        if count > 1:
            errors.append(f"duplicate base index {idx} ({count} entries)")

    # Every consumer that maps a PNG's pixels back to palette indices
    # (tools/build_sprinter_piece_tiles.py, tools/build_sprinter_ui_assets.
    # py) inverts this table into a {rgb: index} dict. Two base entries
    # sharing an RGB value would collapse silently there -- one index would
    # simply never be produced, and the miscoding would only become visible
    # much later, when a theme re-tints one of the two.
    rgb_owners: dict[tuple[int, int, int], list[int]] = {}
    for idx, rgb in sorted(base_rgb.items()):
        rgb_owners.setdefault(rgb, []).append(idx)
    for rgb, owners in sorted(rgb_owners.items()):
        if len(owners) > 1:
            errors.append(
                f"duplicate base RGB #{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X} shared by "
                f"index(es) {', '.join(str(i) for i in owners)} -- the packers invert "
                "the palette into an {rgb: index} map, so a shared colour makes one "
                "of these indices unreachable"
            )
    missing = sorted(set(range(REQUIRED_BASE_COUNT)) - set(indices_seen))
    if missing:
        errors.append(f"missing base index(es): {', '.join(str(i) for i in missing)}")
    if len(base) != REQUIRED_BASE_COUNT:
        errors.append(f"base has {len(base)} entries, expected {REQUIRED_BASE_COUNT}")

    if not (MIN_THEME_COUNT <= len(themes) <= MAX_THEME_COUNT):
        errors.append(
            f"theme count {len(themes)} out of range "
            f"{MIN_THEME_COUNT}..{MAX_THEME_COUNT}"
        )

    theme_key_sets: list[frozenset] = []
    theme_rgb: list[dict[int, tuple[int, int, int]]] = []
    for theme in themes:
        name = theme["name"]
        if not name:
            errors.append("theme name must not be empty")
        if len(name.encode("ascii", errors="replace")) > MAX_THEME_NAME_LEN:
            errors.append(
                f"theme {name!r}: name longer than {MAX_THEME_NAME_LEN} ASCII bytes "
                f"(the blob's name field is {THEME_NAME_FIELD_LEN} bytes and its last "
                "byte must stay NUL -- scene_draw_status prints the field in place as "
                "an ASCIIZ string)"
            )
        try:
            name.encode("ascii")
        except UnicodeEncodeError:
            errors.append(f"theme {name!r}: name is not pure ASCII")

        keys: set[int] = set()
        rgb_by_index: dict[int, tuple[int, int, int]] = {}
        for key_str, rgb_str in theme["entries"].items():
            try:
                idx = int(key_str)
            except ValueError:
                errors.append(f"theme {name!r}: non-integer index key {key_str!r}")
                continue
            if idx not in THEMEABLE_INDICES:
                errors.append(
                    f"theme {name!r}: index {idx} is not themeable "
                    f"(allowed: {sorted(THEMEABLE_INDICES)})"
                )
                continue
            keys.add(idx)
            try:
                rgb_by_index[idx] = _parse_rgb(rgb_str, f"theme {name!r} index {idx}")
            except ValueError as exc:
                errors.append(str(exc))
        # A theme that overrides nothing would reach the resident as
        # entries_per_theme = 0, and scene_theme_next's DJNZ over that count
        # would run 256 times over whatever follows the record, spraying
        # both palette banks. Tool-side rejection is the cheap half of the
        # guard (scene_theme_next has its own defensive check).
        if len(keys) < MIN_THEME_ENTRIES:
            errors.append(
                f"theme {name!r}: overrides no palette indices (need at least "
                f"{MIN_THEME_ENTRIES})"
            )
        theme_key_sets.append(frozenset(keys))
        theme_rgb.append(rgb_by_index)

    if theme_key_sets and len(set(theme_key_sets)) > 1:
        errors.append(
            "themes do not all override the same set of indices "
            f"(saw: {[sorted(s) for s in theme_key_sets]})"
        )

    errors.extend(_validate_piece_sets(palette, base_rgb, theme_rgb))

    if themes and not errors:
        first_rgb = theme_rgb[0]
        for idx, rgb in first_rgb.items():
            if idx in base_rgb and base_rgb[idx] != rgb:
                errors.append(
                    f"theme 0 ({themes[0]['name']!r}) index {idx} does not match "
                    "the base palette -- theme 0 must equal the boot palette"
                )

    return errors


def _validate_piece_sets(palette: dict, base_rgb: dict, theme_rgb: list) -> list[str]:
    """Per-set piece palettes: each set re-defines entries 4-7 (port.md
    section 3.5).

    The collision rule is the interesting part. A set's four colours have
    to differ from each other AND from every other colour that can share
    the screen with them -- 0, 1, 8-15, and the square colours of EVERY
    theme, not just the current one. Two reasons, and the first is the one
    that bites silently: every packer inverts the palette into an
    {rgb: index} map, so a duplicated value makes one index unreachable
    and the artist's pixel is quietly encoded as the other entry. The
    second is simply what it would look like -- a piece the exact colour
    of the board or of a marker."""
    errors: list[str] = []
    piece_sets = palette["piece_sets"]

    if not (MIN_PIECE_SET_COUNT <= len(piece_sets) <= MAX_PIECE_SET_COUNT):
        errors.append(
            f"piece set count {len(piece_sets)} out of range "
            f"{MIN_PIECE_SET_COUNT}..{MAX_PIECE_SET_COUNT}"
        )

    # Everything a piece colour must stay clear of, as {rgb: description}.
    neighbours: dict[tuple[int, int, int], str] = {}
    for idx, rgb in sorted(base_rgb.items()):
        if idx not in PIECE_SET_INDICES:
            neighbours.setdefault(rgb, f"base index {idx}")
    for theme, rgb_by_index in zip(palette["themes"], theme_rgb):
        for idx, rgb in sorted(rgb_by_index.items()):
            neighbours.setdefault(rgb, f"theme {theme['name']!r} index {idx}")

    for set_index, piece_set in enumerate(piece_sets):
        name = piece_set["name"]
        where = f"piece set {name!r}"
        if not isinstance(name, str) or not name:
            errors.append("piece set name must be a non-empty string")
            continue
        try:
            name.encode("ascii")
        except UnicodeEncodeError:
            errors.append(f"{where}: name is not pure ASCII")

        keys: set[int] = set()
        rgb_by_index: dict[int, tuple[int, int, int]] = {}
        for key_str, rgb_str in piece_set["entries"].items():
            try:
                idx = int(key_str)
            except ValueError:
                errors.append(f"{where}: non-integer index key {key_str!r}")
                continue
            keys.add(idx)
            try:
                rgb_by_index[idx] = _parse_rgb(rgb_str, f"{where} index {idx}")
            except ValueError as exc:
                errors.append(str(exc))
        if keys != set(PIECE_SET_INDICES):
            errors.append(
                f"{where}: overrides indices {sorted(keys)}, must override exactly "
                f"{sorted(PIECE_SET_INDICES)} (a set owns the piece colours and "
                "nothing else)"
            )

        owners: dict[tuple[int, int, int], list[int]] = {}
        for idx, rgb in sorted(rgb_by_index.items()):
            owners.setdefault(rgb, []).append(idx)
        for rgb, sharing in sorted(owners.items()):
            if len(sharing) > 1:
                errors.append(
                    f"{where}: #{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X} is used by "
                    f"index(es) {', '.join(str(i) for i in sharing)} -- a set's four "
                    "colours must differ from each other"
                )
            if rgb in neighbours:
                errors.append(
                    f"{where}: #{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X} (index "
                    f"{sharing[0]}) collides with {neighbours[rgb]} -- a piece colour "
                    "may not repeat a board, marker or UI colour (the packers invert "
                    "the palette into an {rgb: index} map, so one of the two indices "
                    "would become unreachable)"
                )

        # Set 0 is what boots, so it has to be the base palette itself --
        # same argument as theme 0, and without it the very first frame
        # would draw set 0's tiles through somebody else's colours.
        if set_index == 0:
            for idx, rgb in sorted(rgb_by_index.items()):
                if idx in base_rgb and base_rgb[idx] != rgb:
                    errors.append(
                        f"{where}: index {idx} does not match the base palette -- "
                        "piece set 0 must equal the boot palette"
                    )

    return errors


def base_rows(palette: dict) -> list[tuple[int, str, tuple[int, int, int]]]:
    rows = []
    for entry in sorted(palette["base"], key=lambda e: e["index"]):
        rows.append((entry["index"], entry["name"], _parse_rgb(entry["rgb"], "base")))
    return rows


def render_inc(palette: dict) -> str:
    guard = "SPRINTER_PALETTE_BASE_INC"
    lines = [
        f"; {GENERATED_BANNER}",
        "",
        f"        IFNDEF {guard}",
        f"        DEFINE {guard}",
        "",
        "palette_rgb:",
    ]
    for idx, name, (r, g, b) in base_rows(palette):
        lines.append(f"        DB 0x{r:02X},0x{g:02X},0x{b:02X}        ; {idx} {name}")
    lines.append("")
    lines.append("        ENDIF")
    lines.append("")
    return "\n".join(lines)


def render_piece_sets_inc(palette: dict) -> str:
    """The per-set piece palettes as a z88dk-z80asm include.

    Shaped like palette_base.inc rather than like the theme BLOB on
    purpose: the theme blob went into the assets page for S4's scene demo
    and no shipped code ever read it, while the boot palette's .inc is
    read by video.asm every day. The consumer (a piece_set_apply routine
    next to theme_set_squares) lands with the set-selection UI -- port.md
    section 3.5 and stage S14; this generator is written first so the data
    format is settled and gated before the Z80 side exists, the same split
    build_sprinter_about.py had before S9."""
    guard = "SPRINTER_PIECE_SET_PALETTES_INC"
    piece_sets = palette["piece_sets"]
    lines = [
        f"; {GENERATED_BANNER}",
        "",
        f"        IFNDEF {guard}",
        f"        DEFINE {guard}",
        "",
        f"PIECE_SET_COUNT EQU {len(piece_sets)}",
        "",
        "; One record per set, in selected_next_sets.json order: entries 4,5,6,7",
        "; as R,G,B triples -- 12 bytes per set, copied into palette_rgb+4*3.",
        "piece_set_rgb:",
    ]
    for set_index, piece_set in enumerate(piece_sets):
        lines.append(f"        ; {set_index} {piece_set['name']}")
        for idx in sorted(PIECE_SET_INDICES):
            r, g, b = _parse_rgb(piece_set["entries"][str(idx)], "piece set")
            lines.append(f"        DB 0x{r:02X},0x{g:02X},0x{b:02X}        ; {idx}")
    lines.append("")
    lines.append("        ENDIF")
    lines.append("")
    return "\n".join(lines)


def build_theme_blob(palette: dict) -> bytes:
    themes = palette["themes"]
    if not themes:
        raise ValueError("no themes to pack")
    keys = sorted(int(k) for k in themes[0]["entries"])
    entries_per_theme = len(keys)
    if entries_per_theme < MIN_THEME_ENTRIES:
        raise ValueError("themes override no palette indices")
    out = bytearray()
    out.append(1)                      # format
    out.append(len(themes))            # theme count
    out.append(entries_per_theme)      # entries per theme
    out.append(0)                      # reserved
    for theme in themes:
        name_bytes = theme["name"].encode("ascii")
        if len(name_bytes) > MAX_THEME_NAME_LEN:
            # Belt and braces: validate_palette rejects this first, but
            # truncating here instead would silently produce a record with
            # no NUL terminator (the exact defect the length cap exists to
            # prevent), so refuse rather than trim.
            raise ValueError(
                f"theme {theme['name']!r}: name needs a NUL terminator inside the "
                f"{THEME_NAME_FIELD_LEN}-byte field (max {MAX_THEME_NAME_LEN} chars)"
            )
        out += name_bytes + bytes(THEME_NAME_FIELD_LEN - len(name_bytes))
        for idx in keys:
            r, g, b = _parse_rgb(theme["entries"][str(idx)], "theme")
            out += bytes([idx, r, g, b])
    return bytes(out)


def decode_theme_blob(blob: bytes) -> dict:
    if len(blob) < 4:
        raise ValueError("theme blob too short for header")
    fmt, count, entries_per_theme, _reserved = blob[0], blob[1], blob[2], blob[3]
    if fmt != 1:
        raise ValueError(f"unknown theme blob format {fmt}")
    stride = THEME_NAME_FIELD_LEN + entries_per_theme * 4
    expected = 4 + count * stride
    if len(blob) < expected:
        raise ValueError(f"theme blob is {len(blob)} bytes, expected >= {expected}")
    themes = []
    offset = 4
    for _ in range(count):
        field = blob[offset:offset + THEME_NAME_FIELD_LEN]
        if field[-1] != 0:
            raise ValueError(
                "theme name field has no NUL terminator -- the Z80 side prints it "
                "in place as an ASCIIZ string"
            )
        name = field.rstrip(b"\x00").decode("ascii")
        entries = {}
        eo = offset + THEME_NAME_FIELD_LEN
        for _e in range(entries_per_theme):
            idx, r, g, b = blob[eo:eo + 4]
            entries[str(idx)] = f"#{r:02X}{g:02X}{b:02X}"
            eo += 4
        themes.append({"name": name, "entries": entries})
        offset += stride
    return {"format": fmt, "themes": themes}


def load_palette_file(path: Path) -> dict:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return parse_palette(raw)


# ---------------------------------------------------------------------------
# Self-test: a clean fixture must validate, and each fixture with exactly one
# invariant deliberately broken must be rejected (gen_sprinter_render_layout.
# py pattern).
# ---------------------------------------------------------------------------

def _clean_fixture() -> dict:
    raw = {
        "base": [
            {"index": 0, "name": "bg", "rgb": "#000000"},
            {"index": 1, "name": "text", "rgb": "#E8E8E8"},
            {"index": 2, "name": "square_light", "rgb": "#F0D9B5"},
            {"index": 3, "name": "square_dark", "rgb": "#B58863"},
            {"index": 4, "name": "white_body", "rgb": "#F8F8F0"},
            {"index": 5, "name": "white_outline", "rgb": "#3A3A3A"},
            {"index": 6, "name": "black_body", "rgb": "#2E2E2E"},
            {"index": 7, "name": "black_outline", "rgb": "#D8D8D0"},
            {"index": 8, "name": "hud_select", "rgb": "#FFD24A"},
            {"index": 9, "name": "hud_hint", "rgb": "#39C15A"},
            {"index": 10, "name": "hud_lastmove", "rgb": "#4A90D9"},
            {"index": 11, "name": "hud_error", "rgb": "#D6453A"},
            {"index": 12, "name": "hud_success", "rgb": "#3AD68C"},
            {"index": 13, "name": "hud_muted", "rgb": "#707070"},
            {"index": 14, "name": "accent", "rgb": "#00BEFE"},
            {"index": 15, "name": "cursor", "rgb": "#FF3D7F"},
        ],
        "themes": [
            {"name": "BROWN", "entries": {"2": "#F0D9B5", "3": "#B58863"}},
            {"name": "BLUE", "entries": {"2": "#DEE3E6", "3": "#8CA2AD"}},
        ],
        "piece_sets": [
            {"name": "setzero", "entries": {"4": "#F8F8F0", "5": "#3A3A3A",
                                             "6": "#2E2E2E", "7": "#D8D8D0"}},
            {"name": "setone", "entries": {"4": "#EFD6A8", "5": "#4B2E14",
                                            "6": "#3B2410", "7": "#C9A46B"}},
        ],
    }
    return parse_palette(raw)


def self_test() -> None:
    clean = _clean_fixture()
    errors = validate_palette(clean)
    if errors:
        raise SystemExit(
            "[ERR] palette self-test: clean fixture rejected: " + "; ".join(errors)
        )

    inc1 = render_inc(clean)
    inc2 = render_inc(_clean_fixture())
    if inc1 != inc2:
        raise SystemExit("[ERR] palette self-test: .inc rendering is not deterministic")
    if "palette_rgb:" not in inc1 or "; 14 accent" not in inc1:
        raise SystemExit("[ERR] palette self-test: .inc missing expected content")

    sets1 = render_piece_sets_inc(clean)
    sets2 = render_piece_sets_inc(_clean_fixture())
    if sets1 != sets2:
        raise SystemExit(
            "[ERR] palette self-test: piece-set .inc rendering is not deterministic"
        )
    if "PIECE_SET_COUNT EQU 2" not in sets1 or "piece_set_rgb:" not in sets1:
        raise SystemExit(
            "[ERR] palette self-test: piece-set .inc missing expected content"
        )

    blob1 = build_theme_blob(clean)
    blob2 = build_theme_blob(_clean_fixture())
    if blob1 != blob2:
        raise SystemExit("[ERR] palette self-test: theme blob is not deterministic")
    if blob1[4 + THEME_NAME_FIELD_LEN - 1] != 0:
        raise SystemExit(
            "[ERR] palette self-test: theme name field is not NUL-terminated"
        )
    decoded = decode_theme_blob(blob1)
    if decoded["themes"][0]["name"] != "BROWN":
        raise SystemExit("[ERR] palette self-test: theme blob round-trip lost data")
    if decoded["themes"][0]["entries"] != clean["themes"][0]["entries"]:
        raise SystemExit(
            "[ERR] palette self-test: theme blob round-trip does not match source"
        )

    def broken(mutate):
        fixture = _clean_fixture()
        mutate(fixture)
        return fixture

    cases = {
        "missing base index": (
            lambda f: f["base"].remove(next(e for e in f["base"] if e["index"] == 5)),
            "missing base index",
        ),
        "duplicate base index": (
            lambda f: f["base"].append(dict(f["base"][0])),
            "duplicate base index",
        ),
        "base index out of range": (
            lambda f: f["base"][0].__setitem__("index", 16),
            "out of range",
        ),
        "bad rgb hex": (
            lambda f: f["base"][0].__setitem__("rgb", "not-a-color"),
            "invalid RGB hex",
        ),
        "zero themes": (
            lambda f: f["themes"].clear(),
            "theme count",
        ),
        "too many themes": (
            lambda f: f["themes"].extend(
                [dict(f["themes"][0], name=f"T{i}") for i in range(8)]
            ),
            "theme count",
        ),
        "theme name too long": (
            lambda f: f["themes"][0].__setitem__("name", "WAYTOOLONGNAME"),
            "name longer than",
        ),
        # Exactly the field width is the interesting boundary: it fits the
        # blob but leaves no NUL, so the status bar would print past the
        # record. One character shorter must still pass (checked below).
        "theme name exactly the field width": (
            lambda f: f["themes"][0].__setitem__("name", "A" * THEME_NAME_FIELD_LEN),
            "name longer than",
        ),
        "duplicate base rgb": (
            lambda f: next(
                e for e in f["base"] if e["index"] == 12
            ).__setitem__("rgb", next(e for e in f["base"] if e["index"] == 11)["rgb"]),
            "duplicate base RGB",
        ),
        "non-ascii base name": (
            lambda f: f["base"][0].__setitem__("name", "фон"),
            "not pure ASCII",
        ),
        "theme overrides nothing": (
            lambda f: [t["entries"].clear() for t in f["themes"]],
            "overrides no palette indices",
        ),
        "theme key set mismatch": (
            lambda f: f["themes"][1]["entries"].update({"8": "#FFFFFF"}),
            "do not all override the same set",
        ),
        "theme key not themeable": (
            lambda f: f["themes"][0]["entries"].update({"0": "#123456"}),
            "not themeable",
        ),
        "theme 0 mismatches base": (
            lambda f: f["themes"][0]["entries"].__setitem__("2", "#123456"),
            "must equal the boot palette",
        ),
        "no piece sets": (
            lambda f: f["piece_sets"].clear(),
            "piece set count",
        ),
        "piece set overrides the wrong indices": (
            lambda f: f["piece_sets"][1]["entries"].__setitem__("8", "#123456"),
            "must override exactly",
        ),
        "piece set 0 mismatches base": (
            lambda f: f["piece_sets"][0]["entries"].__setitem__("4", "#123456"),
            "piece set 0 must equal the boot palette",
        ),
        "piece set repeats a colour inside itself": (
            lambda f: f["piece_sets"][1]["entries"].__setitem__(
                "5", f["piece_sets"][1]["entries"]["4"]
            ),
            "must differ from each other",
        ),
        "piece colour collides with a marker colour": (
            lambda f: f["piece_sets"][1]["entries"].__setitem__("4", "#FFD24A"),
            "collides with base index 8",
        ),
        "piece colour collides with a theme's square colour": (
            lambda f: f["piece_sets"][1]["entries"].__setitem__("4", "#8CA2AD"),
            "collides with theme 'BLUE' index 3",
        ),
        "non-ascii piece set name": (
            lambda f: f["piece_sets"][1].__setitem__("name", "набор"),
            "not pure ASCII",
        ),
    }
    for label, (mutate, needle) in cases.items():
        fixture = broken(mutate)
        errors = validate_palette(fixture)
        if not any(needle in error for error in errors):
            raise SystemExit(
                f"[ERR] palette self-test: broken fixture not rejected with the "
                f"expected diagnostic ({label}: wanted {needle!r}, got {errors})"
            )

    # ... and the longest name that still leaves room for the terminator
    # must be accepted, so the cap above is a boundary and not a blanket ban.
    longest = _clean_fixture()
    longest["themes"][0]["name"] = "A" * MAX_THEME_NAME_LEN
    if validate_palette(longest):
        raise SystemExit(
            f"[ERR] palette self-test: a {MAX_THEME_NAME_LEN}-character theme name "
            "must be accepted"
        )
    if build_theme_blob(longest)[4 + THEME_NAME_FIELD_LEN - 1] != 0:
        raise SystemExit(
            "[ERR] palette self-test: longest accepted name lost its NUL terminator"
        )

    print("[OK] Sprinter palette self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--palette", type=Path,
                        default=Path("assets/sprinter/palette.json"))
    parser.add_argument("--inc-out", type=Path)
    parser.add_argument("--theme-bin-out", type=Path)
    parser.add_argument("--piece-sets-inc-out", type=Path,
                        help="per-set piece palettes as a z80asm include "
                             "(consumer lands with stage S14; see the module "
                             "docstring)")
    parser.add_argument("--check", action="store_true",
                        help="validate only, do not write output files")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    palette = load_palette_file(args.palette)
    errors = validate_palette(palette)
    if errors:
        print(f"[ERR] {args.palette}: palette invariants violated")
        for error in errors:
            print(f"  {error}")
        return 1

    if args.check:
        print(f"[OK] {args.palette}: palette invariants hold")
        return 0

    if not args.inc_out or not args.theme_bin_out:
        raise SystemExit(
            "gen_sprinter_palette: --inc-out and --theme-bin-out are required "
            "unless --check or --self-test is given"
        )

    args.inc_out.parent.mkdir(parents=True, exist_ok=True)
    args.theme_bin_out.parent.mkdir(parents=True, exist_ok=True)
    args.inc_out.write_text(render_inc(palette), encoding="ascii")
    args.theme_bin_out.write_bytes(build_theme_blob(palette))
    print(f"[OK] {args.inc_out}")
    print(f"[OK] {args.theme_bin_out}")
    if args.piece_sets_inc_out:
        args.piece_sets_inc_out.parent.mkdir(parents=True, exist_ok=True)
        args.piece_sets_inc_out.write_text(
            render_piece_sets_inc(palette), encoding="ascii"
        )
        print(f"[OK] {args.piece_sets_inc_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
