#!/usr/bin/env python3
"""Validate and render the Sprinter render core's fixed screen layout.

src/sprinter/render_layout.json is the single source of truth for the
640x256x4bpp screen layout (port.md section 3.4): the six horizontal bands,
the board's cell grid and the info panel's sub-sections. This tool validates
the JSON against the platform invariants (all X even -- the 4bpp packing
alignment rule -- bands/sections tiling their row range with no gaps) and
renders it into asm/sprinter/generated/render_layout.inc (sjasmplus EQUs)
and render_layout.h (C defines), mirroring tools/gen_sprinter_layout.py.

The output is a pure function of the input JSON (no timestamps), so reruns
are byte-identical.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REQUIRED_BANDS = ("BANNER", "MENU", "MOVE", "MAIN", "STATUS", "INPUT")
REQUIRED_PANEL_SECTIONS = ("HEADER", "MOVES", "DIVIDER", "CHAT", "NOTICE")
GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_render_layout.py from "
    "src/sprinter/render_layout.json. Do not edit by hand."
)


def _as_int(value):
    if isinstance(value, int):
        return value
    return int(str(value), 0)


def parse_layout(raw: dict) -> dict:
    bands = [
        {
            "name": b["name"],
            "y": _as_int(b["y"]),
            "h": _as_int(b["h"]),
        }
        for b in raw["bands"]
    ]
    board = raw["board"]
    board_parsed = {
        "x": _as_int(board["x"]),
        "cols": _as_int(board["cols"]),
        "rows": _as_int(board["rows"]),
        "cell_w": _as_int(board["cell_w"]),
        "cell_h": _as_int(board["cell_h"]),
    }
    panel = raw["panel"]
    panel_sections = [
        {
            "name": s["name"],
            "y": _as_int(s["y"]),
            "h": _as_int(s["h"]),
        }
        for s in panel["sections"]
    ]
    panel_parsed = {
        "x": _as_int(panel["x"]),
        "w": _as_int(panel["w"]),
        "sections": panel_sections,
    }
    return {
        "screen_w": _as_int(raw["screen_w"]),
        "screen_h": _as_int(raw["screen_h"]),
        "bands": bands,
        "board": board_parsed,
        "panel": panel_parsed,
    }


def _band(layout: dict, name: str):
    for band in layout["bands"]:
        if band["name"] == name:
            return band
    return None


def _panel_section(layout: dict, name: str):
    for section in layout["panel"]["sections"]:
        if section["name"] == name:
            return section
    return None


def _check_tiling(spans: list[dict], range_start: int, range_end: int,
                   label: str) -> list[str]:
    """Sorted spans (each with y/h) must cover [range_start, range_end) with
    no gaps and no overlaps."""
    errors: list[str] = []
    ordered = sorted(spans, key=lambda s: s["y"])
    cursor = range_start
    for span in ordered:
        if span["h"] <= 0:
            errors.append(f"{label} {span['name']}: non-positive height {span['h']}")
            continue
        if span["y"] != cursor:
            errors.append(
                f"{label} {span['name']}: starts at y={span['y']}, expected "
                f"{cursor} (gap or overlap in {label} tiling)"
            )
        cursor = span["y"] + span["h"]
    if cursor != range_end:
        errors.append(
            f"{label} tiling ends at y={cursor}, expected {range_end}"
        )
    return errors


def validate_layout(layout: dict) -> list[str]:
    errors: list[str] = []
    screen_w = layout["screen_w"]
    screen_h = layout["screen_h"]
    bands = layout["bands"]
    board = layout["board"]
    panel = layout["panel"]

    names = [b["name"] for b in bands]
    if len(names) != len(set(names)):
        dupes = sorted({n for n in names if names.count(n) > 1})
        errors.append(f"duplicate band name(s): {', '.join(dupes)}")
    for required in REQUIRED_BANDS:
        if required not in names:
            errors.append(f"missing required band: {required}")

    errors.extend(_check_tiling(bands, 0, screen_h, "band"))

    section_names = [s["name"] for s in panel["sections"]]
    if len(section_names) != len(set(section_names)):
        dupes = sorted({n for n in section_names if section_names.count(n) > 1})
        errors.append(f"duplicate panel section name(s): {', '.join(dupes)}")
    for required in REQUIRED_PANEL_SECTIONS:
        if required not in section_names:
            errors.append(f"missing required panel section: {required}")

    main = _band(layout, "MAIN")
    if main is not None:
        errors.extend(
            _check_tiling(panel["sections"], main["y"], main["y"] + main["h"],
                          "panel section")
        )

    if board["x"] % 2 != 0:
        errors.append(f"board.x {board['x']} is not even (4bpp alignment)")
    if panel["x"] % 2 != 0:
        errors.append(f"panel.x {panel['x']} is not even (4bpp alignment)")

    board_w = board["cols"] * board["cell_w"]
    board_h = board["rows"] * board["cell_h"]
    if main is not None and board_h != main["h"]:
        errors.append(
            f"board height {board['rows']}x{board['cell_h']}={board_h} "
            f"does not match MAIN band height {main['h']}"
        )

    if board["x"] + board_w > panel["x"]:
        errors.append(
            f"board right edge {board['x'] + board_w} overlaps panel start "
            f"{panel['x']}"
        )
    if panel["x"] + panel["w"] > screen_w:
        errors.append(
            f"panel right edge {panel['x'] + panel['w']} exceeds screen "
            f"width {screen_w}"
        )
    if board["x"] + board_w > screen_w:
        errors.append(
            f"board right edge {board['x'] + board_w} exceeds screen width "
            f"{screen_w}"
        )

    return errors


def compute_symbols(layout: dict) -> dict:
    symbols: dict[str, int] = {
        "SCREEN_W": layout["screen_w"],
        "SCREEN_H": layout["screen_h"],
    }
    for band in layout["bands"]:
        symbols[f"{band['name']}_Y"] = band["y"]
        symbols[f"{band['name']}_H"] = band["h"]

    board = layout["board"]
    symbols["BOARD_X"] = board["x"]
    symbols["BOARD_Y"] = _band(layout, "MAIN")["y"]
    symbols["BOARD_COLS"] = board["cols"]
    symbols["BOARD_ROWS"] = board["rows"]
    symbols["BOARD_CELL_W"] = board["cell_w"]
    symbols["BOARD_CELL_H"] = board["cell_h"]
    symbols["BOARD_W"] = board["cols"] * board["cell_w"]
    symbols["BOARD_H"] = board["rows"] * board["cell_h"]

    panel = layout["panel"]
    symbols["PANEL_X"] = panel["x"]
    symbols["PANEL_Y"] = _band(layout, "MAIN")["y"]
    symbols["PANEL_W"] = panel["w"]
    symbols["PANEL_H"] = _band(layout, "MAIN")["h"]
    for section in panel["sections"]:
        symbols[f"PANEL_{section['name']}_Y"] = section["y"]
        symbols[f"PANEL_{section['name']}_H"] = section["h"]

    return symbols


def render_inc(symbols: dict) -> str:
    guard = "SPRINTER_RENDER_LAYOUT_INC"
    lines = [
        f"; {GENERATED_BANNER}",
        "",
        f"        IFNDEF {guard}",
        f"        DEFINE {guard}",
        "",
    ]
    for name in sorted(symbols):
        value = symbols[name]
        width = 4 if value > 0xFF else 2
        lines.append(f"{name:<20} EQU #{value:0{width}X}")
    lines.append("")
    lines.append("        ENDIF")
    lines.append("")
    return "\n".join(lines)


def render_h(symbols: dict) -> str:
    guard = "SHATRANJ_SPRINTER_RENDER_LAYOUT_H"
    lines = [
        f"/* {GENERATED_BANNER} */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]
    for name in sorted(symbols):
        value = symbols[name]
        lines.append(f"#define SHATRANJ_SPRINTER_{name} {value}")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def load_layout_file(path: Path) -> dict:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return parse_layout(raw)


# ---------------------------------------------------------------------------
# Self-test: a clean fixture must validate, and each fixture with exactly one
# invariant deliberately broken must be rejected (gen_sprinter_layout.py
# pattern).
# ---------------------------------------------------------------------------

def _clean_fixture() -> dict:
    raw = {
        "screen_w": 640,
        "screen_h": 256,
        "bands": [
            {"name": "BANNER", "y": 0, "h": 16},
            {"name": "MENU", "y": 16, "h": 12},
            {"name": "MOVE", "y": 28, "h": 12},
            {"name": "MAIN", "y": 40, "h": 192},
            {"name": "STATUS", "y": 232, "h": 12},
            {"name": "INPUT", "y": 244, "h": 12},
        ],
        "board": {"x": 16, "cols": 8, "rows": 8, "cell_w": 48, "cell_h": 24},
        "panel": {
            "x": 408,
            "w": 232,
            "sections": [
                {"name": "HEADER", "y": 40, "h": 12},
                {"name": "MOVES", "y": 52, "h": 89},
                {"name": "DIVIDER", "y": 141, "h": 8},
                {"name": "CHAT", "y": 149, "h": 71},
                {"name": "NOTICE", "y": 220, "h": 12},
            ],
        },
    }
    return parse_layout(raw)


def self_test() -> None:
    clean = _clean_fixture()
    errors = validate_layout(clean)
    if errors:
        raise SystemExit(
            "[ERR] render-layout self-test: clean fixture rejected: "
            + "; ".join(errors)
        )
    symbols = compute_symbols(clean)
    if symbols["BOARD_X"] + symbols["BOARD_W"] != 400:
        raise SystemExit("[ERR] render-layout self-test: board width derivation wrong")
    if symbols["PANEL_Y"] + symbols["PANEL_H"] != 232:
        raise SystemExit("[ERR] render-layout self-test: panel height derivation wrong")
    inc1 = render_inc(symbols)
    inc2 = render_inc(compute_symbols(_clean_fixture()))
    if inc1 != inc2:
        raise SystemExit("[ERR] render-layout self-test: .inc rendering is not deterministic")

    def broken(mutate):
        fixture = _clean_fixture()
        mutate(fixture)
        return fixture

    cases = {
        "band gap": (
            lambda f: _band(f, "MENU").__setitem__("y", 17),
            "gap or overlap",
        ),
        "bands do not cover screen": (
            lambda f: _band(f, "INPUT").__setitem__("h", 11),
            "expected 256",
        ),
        "missing required band": (
            lambda f: f["bands"].remove(_band(f, "MOVE")),
            "missing required band",
        ),
        "duplicate band name": (
            lambda f: f["bands"].append(dict(_band(f, "MOVE"))),
            "duplicate band",
        ),
        "odd board X": (
            lambda f: f["board"].__setitem__("x", 17),
            "not even",
        ),
        "odd panel X": (
            lambda f: f["panel"].__setitem__("x", 409),
            "not even",
        ),
        "board overlaps panel": (
            lambda f: f["board"].__setitem__("cell_w", 50),
            "overlaps panel",
        ),
        "panel exceeds screen": (
            lambda f: f["panel"].__setitem__("w", 233),
            "exceeds screen",
        ),
        "panel section gap": (
            lambda f: _panel_section(f, "CHAT").__setitem__("y", 150),
            "gap or overlap",
        ),
        "panel sections do not cover MAIN": (
            lambda f: _panel_section(f, "NOTICE").__setitem__("h", 11),
            "expected 232",
        ),
        "missing required panel section": (
            lambda f: f["panel"]["sections"].remove(_panel_section(f, "DIVIDER")),
            "missing required panel section",
        ),
        "board height mismatch with MAIN": (
            lambda f: f["board"].__setitem__("cell_h", 20),
            "does not match MAIN",
        ),
    }
    for label, (mutate, needle) in cases.items():
        fixture = broken(mutate)
        errors = validate_layout(fixture)
        if not any(needle in error for error in errors):
            raise SystemExit(
                f"[ERR] render-layout self-test: broken fixture not rejected "
                f"with the expected diagnostic ({label}: wanted {needle!r}, "
                f"got {errors})"
            )

    print("[OK] Sprinter render-layout self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout", type=Path,
                        default=Path("src/sprinter/render_layout.json"))
    parser.add_argument("--inc-out", type=Path)
    parser.add_argument("--h-out", type=Path)
    parser.add_argument("--check", action="store_true",
                        help="validate only, do not write output files")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    layout = load_layout_file(args.layout)
    errors = validate_layout(layout)
    if errors:
        print(f"[ERR] {args.layout}: render-layout invariants violated")
        for error in errors:
            print(f"  {error}")
        return 1

    if args.check:
        print(f"[OK] {args.layout}: render-layout invariants hold")
        return 0

    if not args.inc_out or not args.h_out:
        raise SystemExit(
            "gen_sprinter_render_layout: --inc-out and --h-out are required "
            "unless --check or --self-test is given"
        )

    symbols = compute_symbols(layout)
    args.inc_out.parent.mkdir(parents=True, exist_ok=True)
    args.h_out.parent.mkdir(parents=True, exist_ok=True)
    args.inc_out.write_text(render_inc(symbols), encoding="ascii")
    args.h_out.write_text(render_h(symbols), encoding="ascii")
    print(f"[OK] {args.inc_out}")
    print(f"[OK] {args.h_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
