#!/usr/bin/env python3
"""Bridge the resident C image's symbol table into z88dk-linkable defc's.

Mirrors tools/gen_overlay_defs.py's role for the ZX/Next overlay ABI, and
tools/gen_sprinter_platform_defs.py's role for the sjasmplus platform
primitives -- but the source here is build/sprinter/resident_c.map (z88dk's
own map format, "_NAME = $ADDR ; ..."), and the symbols are C functions/data
the resident C image (src/sprinter/main.c + src/common/protocol/*.c) already
links once. Overlay C sources (src/spectrum/overlay/*_ovl.c, shared
byte-for-byte with ZX/Next) call some of that same portable common/ code --
control_ovl.c calls netchess_after_prefix and references the
NETCHESS_PROTO_* string constants, for instance. Duplicating game_protocol.c
+ mqtt_session_protocol.c into every overlay's own 2 KiB slot would waste
most of the slot on the same bytes repeated 15 times; this tool lets each
overlay EXTERN the resident's one copy instead, the same way
overlay_loader_sprinter.asm EXTERNs ovl_copy_slot from platform_defs.asm.

The output is a pure function of the input .map file (no timestamps), so
reruns are byte-identical -- same contract as the other two gen_sprinter_*
tools.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Curated allowlist: only these resident C symbols are exposed to overlay
# C sources. Adding a new cross-boundary call means adding its name here --
# same discipline as PLATFORM_SYMBOLS/REQUIRED_SYMBOLS elsewhere.
OVERLAY_RESIDENT_SYMBOLS = [
    # game_protocol.c / mqtt_session_protocol.c -- control_ovl.c's protocol
    # classifier (SPECTRUM_OVL_CONTROL=14u) needs both the string-prefix
    # matcher and the token constants it matches against.
    "netchess_after_prefix",
    "netchess_mqtt_session_parse_u16_token",
    "NETCHESS_PROTO_ACK_PREFIX",
    "NETCHESS_PROTO_NACK_PREFIX",
    "NETCHESS_PROTO_MOVE_PREFIX",
    "NETCHESS_PROTO_CHAT_PREFIX",
    "NETCHESS_PROTO_DRAW",
    "NETCHESS_PROTO_CANCEL_DRAW",
    "NETCHESS_PROTO_CANCEL_RESET",
    "NETCHESS_PROTO_ACK_RESIGN",
    "NETCHESS_PROTO_GAME_START",
    "NETCHESS_PROTO_NACK_RESET",
    "NETCHESS_PROTO_BYE",
    "NETCHESS_PROTO_TAKEBACK_PREFIX",
    "NETCHESS_PROTO_ACK_PING",
]

GENERATED_BANNER = (
    "Generated by tools/gen_sprinter_overlay_defs.py from the resident C "
    "image's .map file. Do not edit by hand."
)

# z88dk map lines: "_name    = $ADDR ; addr, public, ...". C symbols always
# carry the leading underscore z88dk adds; the allowlist below omits it (to
# read the same as the C source) and this parser strips it back off so both
# sides agree on one canonical (unprefixed) key.
MAP_LINE = re.compile(r"^_(\S+)\s+=\s+\$([0-9A-Fa-f]+)\s*;")


class OverlayDefsError(Exception):
    pass


def parse_map(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = MAP_LINE.match(line.strip())
            if match:
                symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def render(symbols: dict[str, int], names: list[str]) -> str:
    missing = [name for name in names if name not in symbols]
    if missing:
        raise OverlayDefsError(
            "missing resident symbol(s) (add to SPRINTER_RESIDENT_C_SRC or "
            "drop from OVERLAY_RESIDENT_SYMBOLS): " + ", ".join(missing)
        )
    lines = [f";; {GENERATED_BANNER}",
             ";; z88dk-z80asm syntax (consumed by overlay C sources linked "
             "separately from the resident, e.g. entry_control_sprinter.asm)",
             ""]
    for name in names:
        addr = symbols[name]
        lines.append(f"PUBLIC _{name}")
        lines.append(f"defc _{name} = ${addr:04X}")
    lines.append("")
    return "\n".join(lines)


def _clean_fixture() -> str:
    return (
        "_netchess_after_prefix          = $4259 ; addr, public, , "
        "src_common_protocol_game_protocol_c, code_compiler, "
        "src/common/protocol/game_protocol.c::netchess_after_prefix::0::0:37\n"
        "_netchess_mqtt_session_parse_u16_token = $4688 ; addr, public, , "
        "src_common_protocol_mqtt_session_protocol_c, code_compiler, "
        "src/common/protocol/mqtt_session_protocol.c::"
        "netchess_mqtt_session_parse_u16_token::0::0:5\n"
        "_NETCHESS_PROTO_ACK_PREFIX      = $49D9 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:12\n"
        "_NETCHESS_PROTO_NACK_PREFIX     = $49DE ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:13\n"
        "_NETCHESS_PROTO_MOVE_PREFIX     = $49E4 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:14\n"
        "_NETCHESS_PROTO_CHAT_PREFIX     = $49EA ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:15\n"
        "_NETCHESS_PROTO_DRAW            = $49F0 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:16\n"
        "_NETCHESS_PROTO_CANCEL_DRAW     = $49F5 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:17\n"
        "_NETCHESS_PROTO_CANCEL_RESET    = $4A01 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:18\n"
        "_NETCHESS_PROTO_ACK_RESIGN      = $4A0E ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:19\n"
        "_NETCHESS_PROTO_GAME_START      = $4A19 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:20\n"
        "_NETCHESS_PROTO_NACK_RESET      = $4A24 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:21\n"
        "_NETCHESS_PROTO_BYE             = $4A2F ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:22\n"
        "_NETCHESS_PROTO_TAKEBACK_PREFIX = $4A33 ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:23\n"
        "_NETCHESS_PROTO_ACK_PING        = $4A3D ; addr, public, , "
        "src_common_protocol_game_protocol_c, rodata_compiler, "
        "src/common/protocol/game_protocol.c:24\n"
        "i_15                            = $4259 ; addr, local, , "
        "src_common_protocol_game_protocol_c, code_compiler, "
        "src/common/protocol/game_protocol.c::netchess_after_prefix::0::0:37\n"
    )


def self_test() -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        map_path = Path(tmp) / "clean.map"
        map_path.write_text(_clean_fixture(), encoding="ascii")
        symbols = parse_map(map_path)

        if symbols.get("netchess_after_prefix") != 0x4259:
            raise SystemExit("[ERR] overlay-defs self-test: function symbol not parsed")
        if symbols.get("NETCHESS_PROTO_ACK_PREFIX") != 0x49D9:
            raise SystemExit("[ERR] overlay-defs self-test: data symbol not parsed")
        # z88dk's compiler-local labels (i_15, no leading underscore) must
        # not crash the parse or leak into the allowlist-checked symbol set.
        if "i_15" in symbols:
            raise SystemExit("[ERR] overlay-defs self-test: local label wrongly captured")

        out1 = render(symbols, OVERLAY_RESIDENT_SYMBOLS)
        out2 = render(symbols, OVERLAY_RESIDENT_SYMBOLS)
        if out1 != out2:
            raise SystemExit("[ERR] overlay-defs self-test: rendering is not deterministic")
        if "PUBLIC _netchess_after_prefix" not in out1:
            raise SystemExit("[ERR] overlay-defs self-test: underscored name missing")
        if "defc _netchess_after_prefix = $4259" not in out1:
            raise SystemExit("[ERR] overlay-defs self-test: address mismatch")
        if "defc _NETCHESS_PROTO_ACK_PREFIX = $49D9" not in out1:
            raise SystemExit("[ERR] overlay-defs self-test: data symbol address mismatch")

        try:
            render(symbols, OVERLAY_RESIDENT_SYMBOLS + ["totally_missing"])
        except OverlayDefsError as exc:
            if "totally_missing" not in str(exc):
                raise SystemExit(
                    "[ERR] overlay-defs self-test: wrong missing-symbol diagnostic"
                )
        else:
            raise SystemExit(
                "[ERR] overlay-defs self-test: missing symbol was not rejected"
            )

    print("[OK] Sprinter overlay-defs self-test")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path, help="resident_c.map to read")
    parser.add_argument("--out", type=Path, help="overlay_defs.asm to write")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0

    if not args.map or not args.out:
        raise SystemExit(
            "gen_sprinter_overlay_defs: --map and --out are required unless --self-test"
        )

    symbols = parse_map(args.map)
    try:
        text = render(symbols, OVERLAY_RESIDENT_SYMBOLS)
    except OverlayDefsError as exc:
        print(f"[ERR] {args.map}: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="ascii")
    print(f"[OK] {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
