#!/usr/bin/env python3
"""Generate matching assembler and C constants for fixed Sprinter WIN2 state."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_layout(path: Path) -> tuple[dict[str, int], int, int]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    symbols = {str(k): int(v, 0) if isinstance(v, str) else int(v)
               for k, v in raw["symbols"].items()}
    stack_top = int(raw["stack_top"], 0)
    stack_headroom = int(raw["stack_headroom"], 0)
    raw_sizes = raw.get("symbol_sizes", {})
    unknown_sizes = sorted(set(raw_sizes) - set(symbols))
    if unknown_sizes:
        raise ValueError(
            "fixed-layout sizes name unknown symbols: " + ", ".join(unknown_sizes)
        )
    sizes = {
        name: int(raw_sizes.get(name, 1), 0)
        if isinstance(raw_sizes.get(name, 1), str)
        else int(raw_sizes.get(name, 1))
        for name in symbols
    }
    aliases = {str(name): str(target)
               for name, target in raw.get("aliases", {}).items()}
    for name, target in aliases.items():
        if name not in symbols or target not in symbols or symbols[name] != symbols[target]:
            raise ValueError(f"invalid fixed-layout alias {name} -> {target}")
    addresses = [address for name, address in symbols.items() if name not in aliases]
    if len(addresses) != len(set(addresses)):
        raise ValueError("fixed-layout symbols contain duplicate addresses")
    for name, address in symbols.items():
        if not 0x8000 <= address < stack_top - stack_headroom:
            raise ValueError(f"{name}=0x{address:04X} is outside persistent WIN2")
    if stack_top != 0xBFF0 or stack_top - stack_headroom < 0x8000:
        raise ValueError("invalid Sprinter stack contract")
    if max(addresses) >= stack_top - stack_headroom:
        raise ValueError("fixed WIN2 state enters the required stack headroom")
    symbol_ranges: list[tuple[int, int, str]] = []
    for name, address in symbols.items():
        if name in aliases:
            continue
        size = sizes[name]
        end = address + size
        if size <= 0 or end > stack_top - stack_headroom:
            raise ValueError(f"fixed symbol {name} is outside WIN2/headroom")
        symbol_ranges.append((address, end, name))
    overlap_groups = [set(str(name) for name in group)
                      for group in raw.get("overlap_groups", [])]
    ordered_ranges = sorted(symbol_ranges)
    for index, previous in enumerate(ordered_ranges):
        for current in ordered_ranges[index + 1:]:
            if current[0] >= previous[1]:
                break
            allowed = any(previous[2] in group and current[2] in group
                          for group in overlap_groups)
            if not allowed:
                raise ValueError(
                    f"fixed symbols {previous[2]} and {current[2]} overlap"
                )
    regions: list[tuple[int, int, str]] = []
    for item in raw.get("regions", []):
        name = str(item["name"])
        address = int(item["address"], 0)
        size = int(item["size"], 0)
        end = address + size
        if size <= 0 or address < 0x8000 or end > stack_top - stack_headroom:
            raise ValueError(f"region {name} is outside persistent WIN2/headroom")
        regions.append((address, end, name))
    for previous, current in zip(sorted(regions), sorted(regions)[1:]):
        if previous[1] > current[0]:
            raise ValueError(f"fixed regions {previous[2]} and {current[2]} overlap")
    return symbols, stack_top, stack_headroom


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", type=Path, required=True)
    parser.add_argument("--asm-out", type=Path, required=True)
    parser.add_argument("--c-out", type=Path, required=True)
    args = parser.parse_args()
    try:
        symbols, stack_top, stack_headroom = load_layout(args.layout)
    except (OSError, KeyError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"gen_sprinter_layout: {exc}") from exc

    asm = ["; Generated by tools/gen_sprinter_layout.py; do not edit."]
    c = [
        "/* Generated by tools/gen_sprinter_layout.py; do not edit. */",
        "#ifndef SHATRANJ_SPRINTER_FIXED_LAYOUT_H",
        "#define SHATRANJ_SPRINTER_FIXED_LAYOUT_H",
        "",
    ]
    for name, address in sorted(symbols.items(), key=lambda item: (item[1], item[0])):
        asm.append(f"DEFC {name} = 0x{address:04X}")
        c.append(f"#define {name} 0x{address:04X}u")
    asm.extend([
        f"DEFC SPRINTER_STACK_TOP = 0x{stack_top:04X}",
        f"DEFC SPRINTER_STACK_HEADROOM = 0x{stack_headroom:04X}",
        "",
    ])
    c.extend([
        f"#define SPRINTER_STACK_TOP 0x{stack_top:04X}u",
        f"#define SPRINTER_STACK_HEADROOM 0x{stack_headroom:04X}u",
        "",
        "#endif",
        "",
    ])
    args.asm_out.parent.mkdir(parents=True, exist_ok=True)
    args.c_out.parent.mkdir(parents=True, exist_ok=True)
    args.asm_out.write_text("\n".join(asm), encoding="utf-8")
    args.c_out.write_text("\n".join(c), encoding="utf-8")
    print(f"[OK] Sprinter fixed layout: {len(symbols)} C/ASM symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
