#!/usr/bin/env python3
"""Generate Sprinter resident-bank page thunks and safe WIN2 imports."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from sprinter_slow_ops import slow_ui_flags


THUNK_ORIGIN = 0xA000
THUNK_SIZE = 8


@dataclass(frozen=True)
class ObjectSymbol:
    section: str


def object_symbols(z80nm: str, path: Path) -> tuple[dict[str, ObjectSymbol], set[str]]:
    output = subprocess.run(
        [z80nm, str(path)], check=True, text=True, capture_output=True
    ).stdout
    defined = {
        name: ObjectSymbol(section)
        for name, section in re.findall(
            r"^\s+G\s+[A-Z]\s+\$[0-9A-Fa-f]+:\s+(\S+)\s+\(section ([^)]+)\)",
            output,
            re.MULTILINE,
        )
    }
    undefined = set(re.findall(r"^\s+U\s+(\S+)", output, re.MULTILINE))
    return defined, undefined


def parse_bank(text: str) -> tuple[str, int, tuple[Path, ...]]:
    parts = text.split(":", 2)
    if len(parts) != 3 or not re.fullmatch(r"[a-z][a-z0-9_]*", parts[0]):
        raise ValueError(f"bad bank specification: {text!r}")
    page = int(parts[1], 0)
    objects = tuple(Path(value).resolve() for value in parts[2].split(",") if value)
    if not 0 <= page <= 63 or not objects:
        raise ValueError(f"bad bank specification: {text!r}")
    return parts[0], page, objects


def parse_map(path: Path) -> dict[str, tuple[int, str]]:
    result: dict[str, tuple[int, str]] = {}
    pattern = re.compile(
        r"^([A-Za-z_][A-Za-z0-9_]*)\s+=\s+\$([0-9A-Fa-f]+)\s+;\s*"
        r"[^,]+,([^\n]*)$",
        re.MULTILINE,
    )
    for name, value, rest in pattern.findall(path.read_text(
            encoding="utf-8", errors="replace")):
        fields = [field.strip() for field in rest.split(",")]
        section = fields[3] if len(fields) > 3 else ""
        result[name] = (int(value, 16), section)
    return result


def runtime_externs(path: Path) -> set[str]:
    return set(re.findall(
        r"^EXTERN\s+([A-Za-z_][A-Za-z0-9_]*)\s*$",
        path.read_text(encoding="utf-8", errors="replace"),
        re.MULTILINE,
    ))


def write_thunks(path: Path, exports: list[dict[str, object]],
                 maps: dict[str, dict[str, tuple[int, str]]] | None) -> None:
    lines = [
        "; Generated by tools/gen_sprinter_resident_imports.py; do not edit.",
        f"DEFS 0x{THUNK_ORIGIN - 0x8000:04X}-$,0",
        "",
    ]
    for index, item in enumerate(exports):
        symbol = str(item["symbol"])
        bank = str(item["bank"])
        target = 0
        if maps is not None:
            if symbol not in maps[bank]:
                raise ValueError(f"{bank} map lacks resident export {symbol}")
            target, section = maps[bank][symbol]
            if not section.startswith("code") or not 0x4000 <= target < 0x8000:
                raise ValueError(
                    f"resident export {symbol}=0x{target:04X} is not WIN1 code"
                )
        expected = THUNK_ORIGIN + index * THUNK_SIZE
        lines.extend([
            f"DEFS 0x{expected - 0x8000:04X}-$,0",
            f"PUBLIC {symbol}",
            f"{symbol}:",
            f"    LD A,{int(item['page']) | (0x80 if int(item.get('flags', 0)) & 1 else 0)}",
            "    CALL sprinter_resident_call",
            f"    DEFW 0x{target:04X}",
            "    NOP",
            "",
        ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def discover(args: argparse.Namespace) -> None:
    banks: list[dict[str, object]] = []
    owners: dict[str, tuple[str, int, str] | None] = {}
    for text in args.bank:
        name, page, objects = parse_bank(text)
        defined: dict[str, ObjectSymbol] = {}
        undefined: set[str] = set()
        for obj in objects:
            obj_defined, obj_undefined = object_symbols(args.z80nm, obj)
            for symbol, record in obj_defined.items():
                if symbol in defined:
                    raise ValueError(f"bank {name} defines {symbol} more than once")
                defined[symbol] = record
            undefined.update(obj_undefined)
        bank = {
            "name": name,
            "page": page,
            "objects": [str(path) for path in objects],
            "defined": {symbol: record.section for symbol, record in defined.items()},
            "undefined": sorted(undefined - set(defined)),
        }
        banks.append(bank)
        for symbol, record in defined.items():
            if symbol in owners:
                owners[symbol] = None
            else:
                owners[symbol] = (name, page, record.section)

    required = runtime_externs(args.runtime_source)
    referenced = required.copy()
    for bank in banks:
        referenced.update(str(value) for value in bank["undefined"])
        if bank["name"] != "app":
            for symbol_value in bank["undefined"]:
                symbol = str(symbol_value)
                owned = owners.get(symbol)
                if (owned is not None and owned[0] != bank["name"] and
                        owned[2].startswith("code")):
                    raise ValueError(
                        f"bank {bank['name']} would recursively call "
                        f"{owned[0]} code {symbol}"
                    )
    exports: list[dict[str, object]] = []
    for symbol in sorted(referenced & set(owners)):
        owned = owners[symbol]
        if owned is None:
            continue
        name, page, section = owned
        if section.startswith("code"):
            exports.append({
                "symbol": symbol,
                "bank": name,
                "page": page,
                "flags": slow_ui_flags(symbol) if name == "ui" else 0,
            })
        elif any(symbol in other["undefined"] for other in banks
                 if other["name"] != name):
            if not (section.startswith("data") or section.startswith("bss")):
                raise ValueError(
                    f"cross-bank object {symbol} is in unavailable WIN1 section {section}"
                )

    plan = {"version": 1, "banks": banks, "exports": exports}
    args.plan_out.parent.mkdir(parents=True, exist_ok=True)
    args.plan_out.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n",
                             encoding="utf-8")
    write_thunks(args.thunks_out, exports, None)
    print(f"[OK] Sprinter resident import plan: {len(exports)} WIN1 thunk(s)")


def emit_imports(plan: dict[str, object], runtime: dict[str, tuple[int, str]],
                 maps: dict[str, dict[str, tuple[int, str]]] | None,
                 output_dir: Path) -> None:
    owner: dict[str, tuple[str, str] | None] = {}
    thunk_symbols = {str(item["symbol"]) for item in plan["exports"]}
    for bank in plan["banks"]:
        for symbol, section in bank["defined"].items():
            key = str(symbol)
            value = (str(bank["name"]), str(section))
            owner[key] = None if key in owner else value

    output_dir.mkdir(parents=True, exist_ok=True)
    for bank in plan["banks"]:
        name = str(bank["name"])
        definitions: dict[str, int] = {}
        for symbol_value in bank["undefined"]:
            symbol = str(symbol_value)
            owned = owner.get(symbol)
            if owned is not None and owned[0] != name:
                section = owned[1]
                if section.startswith("code"):
                    if symbol not in thunk_symbols or symbol not in runtime:
                        raise ValueError(f"runtime lacks cross-bank thunk {symbol}")
                    definitions[symbol] = runtime[symbol][0]
                elif section.startswith("data") or section.startswith("bss"):
                    if maps is None:
                        definitions[symbol] = 0x8000
                    else:
                        address, mapped_section = maps[owned[0]][symbol]
                        if not (mapped_section.startswith("data") or
                                mapped_section.startswith("bss")):
                            raise ValueError(f"mutable import {symbol} changed section")
                        if not 0x8000 <= address < 0xC000:
                            raise ValueError(f"mutable import {symbol} leaves WIN2")
                        definitions[symbol] = address
            elif symbol in runtime:
                address = runtime[symbol][0]
                if 0x8000 <= address < 0xC000:
                    definitions[symbol] = address

        lines = [
            "; Generated by tools/gen_sprinter_resident_imports.py; do not edit."
        ]
        for symbol, address in sorted(definitions.items()):
            lines.extend([f"PUBLIC {symbol}", f"DEFC {symbol} = 0x{address:04X}"])
        lines.append("")
        (output_dir / f"{name}_imports.asm").write_text(
            "\n".join(lines), encoding="utf-8")


def finalize(args: argparse.Namespace) -> None:
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    runtime = parse_map(args.runtime_map)
    maps = None
    if args.bank_map:
        maps = {}
        for value in args.bank_map:
            name, path = value.split(":", 1)
            maps[name] = parse_map(Path(path))
        expected = {str(bank["name"]) for bank in plan["banks"]}
        if set(maps) != expected:
            raise ValueError("--bank-map set does not match the resident plan")
    emit_imports(plan, runtime, maps, args.output_dir)
    if maps is not None:
        write_thunks(args.thunks_out, plan["exports"], maps)
    print("[OK] Sprinter resident bank imports generated")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--z80nm", default="z88dk-z80nm")
    parser.add_argument("--bank", action="append", default=[])
    parser.add_argument("--runtime-source", type=Path)
    parser.add_argument("--plan-out", type=Path)
    parser.add_argument("--plan", type=Path)
    parser.add_argument("--runtime-map", type=Path)
    parser.add_argument("--bank-map", action="append", default=[])
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--thunks-out", type=Path)
    args = parser.parse_args()
    try:
        if args.plan:
            if not all((args.runtime_map, args.output_dir, args.thunks_out)):
                parser.error("finalize mode requires runtime map, output dir and thunks")
            finalize(args)
        else:
            if not all((args.bank, args.runtime_source, args.plan_out,
                        args.thunks_out)):
                parser.error("discovery mode requires banks, runtime source, plan and thunks")
            discover(args)
    except (OSError, ValueError, KeyError, json.JSONDecodeError,
            subprocess.CalledProcessError) as exc:
        raise SystemExit(f"gen_sprinter_resident_imports: {exc}") from exc
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
