#!/usr/bin/env python3
"""Generate WIN2 far-call thunks for functions that remain in the base bank."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def map_symbols(text: str) -> dict[str, int]:
    patterns = (
        r"^([A-Za-z_][A-Za-z0-9_]*)\s+=\s+\$([0-9A-Fa-f]+)\b",
        r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([0-9A-Fa-f]+)\b",
    )
    symbols: dict[str, int] = {}
    for pattern in patterns:
        for name, value in re.findall(pattern, text, re.MULTILINE):
            symbols[name] = int(value, 16)
    return symbols


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--map", dest="map_file", type=Path, required=True)
    parser.add_argument("--exports", type=Path, required=True)
    parser.add_argument("--asm-out", type=Path, required=True)
    args = parser.parse_args()
    try:
        symbols = map_symbols(args.map_file.read_text(encoding="utf-8", errors="replace"))
        exports = json.loads(args.exports.read_text(encoding="utf-8"))["exports"]
        lines = ["; Generated by tools/gen_sprinter_thunks.py; do not edit."]
        for item in exports:
            name = str(item["name"])
            thunk = str(item["thunk"])
            if name not in symbols:
                raise ValueError(f"missing base-bank export in map: {name}")
            address = symbols[name]
            if not 0x4000 <= address < 0x8000:
                raise ValueError(f"base export {name}=0x{address:04X} is outside WIN1")
            lines.extend([
                f"PUBLIC {thunk}",
                f"{thunk}:",
                f"    LD HL,0x{address:04X}",
                "    JP sprinter_far_call",
                "",
            ])
    except (OSError, KeyError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"gen_sprinter_thunks: {exc}") from exc
    args.asm_out.parent.mkdir(parents=True, exist_ok=True)
    args.asm_out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] Sprinter far-call thunks: {len(exports)} base export(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
