#!/usr/bin/env python3
"""Render VERSION into asm/sprinter's banner include (S4).

CLAUDE.md rule 5: VERSION is the only source of the version string, and
version literals in code or build rules are forbidden. scene_s4.asm's
banner therefore reads a generated sprinter_banner_msg instead of
embedding a string of its own.

The output is a guarded DATA LABEL, not a DEFINE-with-string-value macro:
that form did not survive sjasmplus's multi-pass resolution reliably at
the full resident's size, even though flag-only DEFINE guards (used
everywhere else here) work fine. Same shape as palette_base.inc's
palette_rgb.

Named sprinter_version.inc, not the generic "version.inc":
extern/esp_net/src/include/version.inc (the uNet submodule's own package
version) sits on the same -I search path and would otherwise shadow it --
sjasmplus resolves INCLUDE by search order, not directory proximity.

Two consumers generate this file -- the Makefile's $(SPRINTER_VERSION_INC)
rule and tools/run_sprinter_z80_tests.sh (into its own private generated
dir) -- which is exactly why the template lives here and not inline in
both: two copies of a printf template are two places to drift.

Output is a pure function of VERSION (no timestamps), so reruns are
byte-identical.
"""

from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = """; Generated by tools/gen_sprinter_version.py from VERSION. Do not edit by hand.

        IFNDEF SPRINTER_VERSION_INC
        DEFINE SPRINTER_VERSION_INC

sprinter_banner_msg: DB "SHATRANJ v{version}",0

        ENDIF
"""


def read_version(path: Path) -> str:
    version = path.read_text(encoding="utf-8").strip()
    if not version:
        raise SystemExit(f"Error: {path} is empty")
    # The string is emitted inside a DB "..." literal: anything that could
    # terminate or escape it has no business in a version number.
    bad = set(version) & set('"\\\n\r')
    if bad or not version.isprintable():
        raise SystemExit(f"Error: {path}: version {version!r} has unusable characters")
    return version


def render_inc(version: str) -> str:
    return TEMPLATE.format(version=version)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-file", type=Path, default=Path("VERSION"))
    parser.add_argument("--inc-out", required=True, type=Path)
    args = parser.parse_args()

    version = read_version(args.version_file)
    args.inc_out.parent.mkdir(parents=True, exist_ok=True)
    args.inc_out.write_text(render_inc(version), encoding="ascii")
    print(f"[OK] {args.inc_out}: v{version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
