#!/usr/bin/env python3
"""Generate declared WIN2 imports and WIN1 far thunks for Sprinter banks."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class MapSymbol:
    address: int
    kind: str
    section: str


def parse_module(text: str) -> tuple[int, str, tuple[Path, ...]]:
    parts = text.split(":", 2)
    if len(parts) != 3:
        raise ValueError(f"bad module specification: {text!r}")
    module_id = int(parts[0], 0)
    inputs = tuple(Path(item).resolve() for item in parts[2].split(",") if item)
    if not 0 <= module_id <= 14 or not inputs:
        raise ValueError(f"invalid module specification: {text!r}")
    return module_id, parts[1], inputs


def parse_map(path: Path) -> dict[str, MapSymbol]:
    symbols: dict[str, MapSymbol] = {}
    pattern = re.compile(
        r"^([A-Za-z_][A-Za-z0-9_]*)\s+=\s+\$([0-9A-Fa-f]+)\s+;\s*([^,]+),([^\n]*)$",
        re.MULTILINE,
    )
    for name, value, kind, rest in pattern.findall(
            path.read_text(encoding="utf-8", errors="replace")):
        fields = [field.strip() for field in rest.split(",")]
        section = fields[3] if len(fields) > 3 else ""
        symbols[name] = MapSymbol(int(value, 16), kind.strip(), section)
    return symbols


def object_symbols(z80nm: str, path: Path) -> tuple[set[str], set[str]]:
    output = subprocess.run(
        [z80nm, str(path)], check=True, text=True, capture_output=True
    ).stdout
    defined = set(re.findall(r"^\s+G\s+[A-Z]\s+\$[0-9A-Fa-f]+:\s+(\S+)",
                             output, re.MULTILINE))
    undefined = set(re.findall(r"^\s+U\s+(\S+)", output, re.MULTILINE))
    return defined, undefined


def thunk_name(symbol: str) -> str:
    return "sprinter_far_import_" + re.sub(r"[^A-Za-z0-9_]", "_", symbol).lstrip("_")


def discover(args: argparse.Namespace) -> None:
    base = parse_map(args.base_map)
    modules = []
    far_symbols: dict[str, dict[str, object]] = {}
    for text in args.module:
        module_id, name, inputs = parse_module(text)
        defined: set[str] = set()
        undefined: set[str] = set()
        for path in inputs:
            obj_defined, obj_undefined = object_symbols(args.z80nm, path)
            defined.update(obj_defined)
            undefined.update(obj_undefined)
        imports = []
        for symbol in sorted(undefined - defined):
            mapped = base.get(symbol)
            if mapped is None:
                resolution = {"kind": "resident", "symbol": symbol}
            elif 0x4000 <= mapped.address < 0x8000:
                if not mapped.section.startswith("code"):
                    raise ValueError(
                        f"module {module_id}: immutable WIN1 import {symbol} "
                        f"from section {mapped.section or '?'}"
                    )
                thunk = thunk_name(symbol)
                resolution = {
                    "kind": "far", "symbol": symbol, "target": mapped.address,
                    "thunk": thunk,
                }
                far_symbols[symbol] = resolution
            elif 0x8000 <= mapped.address < 0xC000:
                resolution = {
                    "kind": "direct", "symbol": symbol,
                    "target": mapped.address,
                }
            else:
                raise ValueError(
                    f"module {module_id}: unsafe import {symbol}=0x{mapped.address:04X}"
                )
            imports.append(resolution)
        modules.append({
            "id": module_id,
            "name": name,
            "objects": [str(path) for path in inputs],
            "imports": imports,
        })

    lines = ["; Generated by tools/gen_sprinter_cold_imports.py; do not edit."]
    for item in sorted(far_symbols.values(), key=lambda value: str(value["symbol"])):
        lines.extend([
            f"PUBLIC {item['thunk']}",
            f"{item['thunk']}:",
            f"    LD HL,0x{int(item['target']):04X}",
            "    JP sprinter_far_call",
            "",
        ])
    args.thunks_out.parent.mkdir(parents=True, exist_ok=True)
    args.thunks_out.write_text("\n".join(lines), encoding="utf-8")
    plan = {"version": 1, "modules": sorted(modules, key=lambda item: item["id"])}
    args.plan_out.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n",
                             encoding="utf-8")
    print(f"[OK] Sprinter cold import plan: {len(far_symbols)} WIN1 thunk(s)")


def finalize(args: argparse.Namespace) -> None:
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    runtime = parse_map(args.runtime_map)
    definitions: dict[str, int] = {}
    for module in plan["modules"]:
        for item in module["imports"]:
            kind = item["kind"]
            symbol = str(item["symbol"])
            if kind == "direct":
                address = int(item["target"])
            elif kind == "far":
                thunk = str(item["thunk"])
                if thunk not in runtime:
                    raise ValueError(f"runtime map lacks generated thunk {thunk}")
                address = runtime[thunk].address
            else:
                if symbol not in runtime:
                    raise ValueError(f"runtime map lacks resident import {symbol}")
                address = runtime[symbol].address
            if not 0x8000 <= address < 0xC000:
                raise ValueError(
                    f"cold import {symbol}=0x{address:04X} is outside permanent WIN2"
                )
            item["address"] = address
            definitions[symbol] = address

    lines = ["; Generated by tools/gen_sprinter_cold_imports.py; do not edit."]
    for symbol, address in sorted(definitions.items()):
        lines.extend([f"PUBLIC {symbol}", f"DEFC {symbol} = 0x{address:04X}"])
    lines.append("")
    args.defs_out.parent.mkdir(parents=True, exist_ok=True)
    args.defs_out.write_text("\n".join(lines), encoding="utf-8")
    args.manifest_out.write_text(
        json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"[OK] Sprinter cold imports: {len(definitions)} declared WIN2 symbol(s)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--z80nm", default="z88dk-z80nm")
    parser.add_argument("--base-map", type=Path)
    parser.add_argument("--module", action="append", default=[])
    parser.add_argument("--thunks-out", type=Path)
    parser.add_argument("--plan-out", type=Path)
    parser.add_argument("--plan", type=Path)
    parser.add_argument("--runtime-map", type=Path)
    parser.add_argument("--defs-out", type=Path)
    parser.add_argument("--manifest-out", type=Path)
    args = parser.parse_args()
    try:
        if args.plan:
            if not all((args.runtime_map, args.defs_out, args.manifest_out)):
                parser.error("finalize mode needs --runtime-map, --defs-out and --manifest-out")
            finalize(args)
        else:
            if not all((args.base_map, args.module, args.thunks_out, args.plan_out)):
                parser.error("discovery mode needs base map, modules, thunks and plan outputs")
            discover(args)
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError,
            json.JSONDecodeError) as exc:
        raise SystemExit(f"gen_sprinter_cold_imports: {exc}") from exc
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
