#!/usr/bin/env python3
"""Assemble and pack stable-ID Sprinter cold modules into 16 KiB banks."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


PAGE_SIZE = 0x4000
WINDOW_BASE = 0x4000
WINDOW_END = 0x8000
MODULE_LIMIT = 0x0800
DESCRIPTOR_SIZE = 8
MAX_OVERLAY_ID = 14
SLOW_OVERLAY_IDS = {10, 12, 13}


@dataclass(frozen=True)
class ModuleSpec:
    overlay_id: int
    name: str
    inputs: tuple[Path, ...]


def parse_spec(text: str) -> ModuleSpec:
    parts = text.split(":", 2)
    if len(parts) != 3:
        raise ValueError(f"bad --module value {text!r}; expected ID:NAME:INPUT[,INPUT]")
    overlay_id = int(parts[0], 0)
    if not 0 <= overlay_id <= MAX_OVERLAY_ID:
        raise ValueError(f"overlay ID {overlay_id} is outside 0..{MAX_OVERLAY_ID}")
    if not re.fullmatch(r"[a-z][a-z0-9_]*", parts[1]):
        raise ValueError(f"invalid module name: {parts[1]!r}")
    inputs = tuple(Path(item).resolve() for item in parts[2].split(",") if item)
    if not inputs:
        raise ValueError(f"module {parts[1]!r} has no inputs")
    return ModuleSpec(overlay_id, parts[1], inputs)


def allocate_modules(sizes: list[int]) -> list[tuple[int, int]]:
    """Return (bank, address) placements using stable first-fit order."""
    placements: list[tuple[int, int]] = []
    bank = 0
    offset = 0
    for size in sizes:
        if not 0 < size <= MODULE_LIMIT:
            raise ValueError(f"cold module size {size} exceeds the 2 KiB ceiling")
        offset = (offset + 1) & ~1
        if offset + size > PAGE_SIZE:
            bank += 1
            offset = 0
        placements.append((bank, WINDOW_BASE + offset))
        offset += size
    return placements


def validate_entry_table(data: bytes, base: int, name: str) -> tuple[int, list[int]]:
    count = data[0]
    table_size = 1 + count * 2
    if count == 0 or table_size > len(data):
        raise ValueError(f"{name}: invalid entry table count {count}")
    entries = [int.from_bytes(data[1 + i * 2:3 + i * 2], "little")
               for i in range(count)]
    for entry in entries:
        if not base + table_size <= entry < base + len(data):
            raise ValueError(
                f"{name}: entry 0x{entry:04X} is outside module "
                f"0x{base:04X}..0x{base + len(data):04X}"
            )
    return count, entries


def assemble(z80asm: str, root: Path, build_dir: Path, spec: ModuleSpec,
             address: int, suffix: str) -> tuple[bytes, Path]:
    output = build_dir / f"{spec.name}{suffix}.bin"
    command_inputs: list[str]
    local_source = build_dir / f"{spec.name}{suffix}.asm"
    if len(spec.inputs) == 1 and spec.inputs[0].suffix.lower() == ".asm":
        shutil.copyfile(spec.inputs[0], local_source)
        command_inputs = [local_source.name]
    else:
        command_inputs = [str(path) for path in spec.inputs]
    command = [
        z80asm, f"-I={root}", f"-I={build_dir}", "-O=.", "-b", "-m",
        f"-r=0x{address:04X}", f"-o={output.name}", *command_inputs,
    ]
    subprocess.run(command, cwd=build_dir, check=True)
    candidates = [output.with_suffix(".map"), local_source.with_suffix(".map")]
    map_path = next((path for path in candidates if path.exists()), candidates[0])
    return output.read_bytes(), map_path


def write_atlas(path: Path, records: dict[int, dict[str, object]]) -> None:
    lines = [
        "; Generated by tools/pack_sprinter_banks.py; do not edit.",
        f"DEFC SPRINTER_ATLAS_MAX_ID = {MAX_OVERLAY_ID}",
        f"DEFC SPRINTER_ATLAS_DESCRIPTOR_SIZE = {DESCRIPTOR_SIZE}",
        "sprinter_overlay_atlas:",
    ]
    for overlay_id in range(MAX_OVERLAY_ID + 1):
        record = records.get(overlay_id)
        if record is None:
            values = [0, 0, 0, 0, 0, 0, 0, 0]
            comment = "unused"
        else:
            base = int(record["base"])
            length = int(record["length"])
            values = [
                1, int(record["payload_page"]), base & 0xFF, base >> 8,
                length & 0xFF, length >> 8, int(record["entry_count"]),
                int(record["flags"]),
            ]
            comment = str(record["name"])
        lines.append(
            "    DEFB " + ",".join(f"0x{value:02X}" for value in values) +
            f" ; id {overlay_id}: {comment}"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def stable_path(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root).as_posix()
    except ValueError:
        return path.name


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--z80asm", default="z80asm")
    parser.add_argument("--module", action="append", required=True)
    parser.add_argument("--resident-page", type=Path, action="append", default=[])
    parser.add_argument("--atlas-out", type=Path, required=True)
    parser.add_argument("--manifest-out", type=Path, required=True)
    parser.add_argument("--page-prefix", type=Path, required=True)
    args = parser.parse_args()

    root = args.root.resolve()
    build_dir = args.build_dir.resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    try:
        specs = sorted((parse_spec(text) for text in args.module),
                       key=lambda spec: spec.overlay_id)
        ids = [spec.overlay_id for spec in specs]
        if len(ids) != len(set(ids)):
            raise ValueError("duplicate cold-module overlay ID")
        probes = [assemble(args.z80asm, root, build_dir, spec, WINDOW_BASE, ".probe")[0]
                  for spec in specs]
        placements = allocate_modules([len(data) for data in probes])
        records: dict[int, dict[str, object]] = {}
        resident_pages = [path.resolve().read_bytes() for path in args.resident_page]
        if any(len(page) != PAGE_SIZE for page in resident_pages):
            raise ValueError("resident bank pages must be exactly 16 KiB")
        cold_pages = [bytearray(PAGE_SIZE)
                      for _ in range(max(bank for bank, _ in placements) + 1)]
        for spec, probe, (bank, base) in zip(specs, probes, placements):
            data, map_path = assemble(args.z80asm, root, build_dir, spec, base, "")
            if len(data) != len(probe):
                raise ValueError(f"{spec.name}: relocation changed module size")
            count, entries = validate_entry_table(data, base, spec.name)
            offset = base - WINDOW_BASE
            cold_pages[bank][offset:offset + len(data)] = data
            records[spec.overlay_id] = {
                "id": spec.overlay_id,
                "name": spec.name,
                "bank": bank,
                "payload_page": bank + 2 + len(resident_pages),
                "base": base,
                "length": len(data),
                "entry_count": count,
                "flags": 1 if spec.overlay_id in SLOW_OVERLAY_IDS else 0,
                "entries": entries,
                "map": stable_path(map_path, root),
                "inputs": [stable_path(path, root) for path in spec.inputs],
            }
        atlas_out = args.atlas_out.resolve()
        manifest_out = args.manifest_out.resolve()
        atlas_out.parent.mkdir(parents=True, exist_ok=True)
        write_atlas(atlas_out, records)
        page_paths = []
        prefix = args.page_prefix.resolve()
        pages = [bytearray(page) for page in resident_pages] + cold_pages
        for index, page in enumerate(pages):
            page_path = Path(f"{prefix}{index}.bin")
            page_path.parent.mkdir(parents=True, exist_ok=True)
            page_path.write_bytes(page)
            page_paths.append(stable_path(page_path, root))
        manifest = {
            "format": "Shatranj Sprinter bank atlas",
            "version": 1,
            "window": [WINDOW_BASE, WINDOW_END],
            "module_limit": MODULE_LIMIT,
            "alignment": 2,
            "page_size": PAGE_SIZE,
            "pages": page_paths,
            "resident_page_count": len(resident_pages),
            "cold_page_count": len(cold_pages),
            "modules": [records[key] for key in sorted(records)],
        }
        manifest_out.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                                encoding="utf-8")
    except (OSError, ValueError, subprocess.CalledProcessError) as exc:
        raise SystemExit(f"pack_sprinter_banks: {exc}") from exc
    print(
        f"[OK] Sprinter bank atlas: {len(args.resident_page)} resident and "
        f"{len(cold_pages)} cold page(s), {len(specs)} modules"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
